WIP [PRODX-24170]: added tests for ConnectionBlock component
Mirantis/lens-extension-cc pull request #1007
Opened 2022-08-03 10:54 UTC by AntonNos

2022-08-03 18:13 UTC, stefcameron requested changes
We need to figure out what's going on with that Input and `user.type()` because the way you've implemented the mock so far isn't calling the consumer's `onChange` and it's making the mock Input stateful when the real one is not.

2022-08-03 18:13 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +  const [inputValue, setinputValue] = useState('');
The problem with this is that the Lens component is not stateful. It doesn't internally manage the input's value as state. It requires the parent or the user of the Input to manage that state. If we make the mock stateful, then we break the rule of keep the mock as close to reality as possible.

The ConnectionBlock already has state to manage the value of the cluster name and URL inputs...

2022-08-05 10:41 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +  const [inputValue, setinputValue] = useState('');
Fixed! Thanks for helping me with that!

2022-08-05 13:39 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +      {!isValid && errorMessage.length && <p>{errorMessage}</p>}
This should be wrapped in a `<div className="errors">`

2022-08-05 13:39 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +const Input = ({ trim, ...props }) => {
Needs an `effect(() => validate(), [])` that runs on first render only.

2022-08-05 13:39 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +    validate(event);
Should validate first, and if there's at least one error found, do not call `onChange()`. That's how Lens does it.

2022-08-05 22:29 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +    validate(event);
Fixed

2022-08-05 22:29 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +const Input = ({ trim, ...props }) => {
Fixed

2022-08-05 22:33 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +      {!isValid && errorMessage.length && <p>{errorMessage}</p>}
Done

2022-08-05 22:43 UTC, stefcameron requested changes
Nearly there!

2022-08-05 22:43 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +        setErrorMessages([errorMessages, validator.message()]);
State updates happen asynchronously, not immediately, so I'm not sure this would work all the time as expected. Also, you're missing a spread in `...errorMessages`.

We should have a local `errors = []` object in which we accumulate errors. Once the loop breaks or ends, then we `setErrorMessages(errors)` (either clearing or setting error(s)).

2022-08-05 22:43 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +      if (errorMessages.length) {
Look at a local `errors` var, not the state var.

2022-08-05 22:43 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +    validate(event);
Should return its local/internal `errors` list, and then we should be using that list here to determine if we'll call `onChange` or not...

2022-08-05 22:43 UTC, stefcameron commented on src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js
> +      const inputName = document.getElementById('lecc-cluster-name');
In general, whenever I have a variable that's an element, I put `El` at the end, like `inputEl` or `inputNameEl`. When it's just `inputName`, that sounds more like it's a string than an element, which could lead someone else working in this code later on to make a wrong assumption and use it incorrectly.

2022-08-05 22:43 UTC, stefcameron commented on src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js
> +      const inputName = document.getElementById('lecc-cluster-name');
Ditto...

2022-08-05 22:43 UTC, stefcameron commented on src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js
> +      const inputUrl = document.getElementById('lecc-cluster-url');
Ditto...

2022-08-05 23:04 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +        setErrorMessages([errorMessages, validator.message()]);
I missed spread, thank. But anyway, we won't use that:slightly_smiling_face:
Local errors was added

2022-08-05 23:05 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +      if (errorMessages.length) {
Fixed

2022-08-05 23:06 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +    validate(event);
Fixed

2022-08-05 23:06 UTC, AntonNos commented on src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js
> +      const inputName = document.getElementById('lecc-cluster-name');
Will take into account, thanks! Fixed

2022-08-05 23:06 UTC, AntonNos commented on src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js
> +      const inputName = document.getElementById('lecc-cluster-name');
Fixed

2022-08-05 23:06 UTC, AntonNos commented on src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js
> +      const inputUrl = document.getElementById('lecc-cluster-url');
Fixed

2022-08-05 23:20 UTC, stefcameron requested changes

2022-08-05 23:20 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +      setErrorMessages(errors);
Shouldn't set this in the loop. Just once right _after_ the loop is done, just before the `return`

2022-08-05 23:20 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +    validate(event);
We're calling `validate(event)` twice now in this function... Probably this call should be dropped.

2022-08-05 23:20 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +  const validate = (event) => {
Instead of passing the `event` object, pass `event.target.value` or `props.value` depending on where you call `validate()` from so that validators are actually run on first render, and then anytime the value changes.

2022-08-05 23:20 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +    }
Should be no need for this.

2022-08-05 23:20 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +  useEffect(() => validate(), []);
Call `validate(props.value)`, which will trigger a lint error that the effect needs to depend on `[props.value]` but let's disable that error for this line only with a comment `// eslint-disable-next-line RULE_NAME -- only run this on first render; run validators in handleChange() afterward` (I forget what the rule name is...)

2022-08-05 23:22 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +      setErrorMessages(errors);
Right, my mistake. Fixed

2022-08-05 23:22 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +    validate(event);
Done

2022-08-05 23:25 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +  const validate = (event) => {
Done

2022-08-05 23:25 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +    }
Correct

2022-08-05 23:27 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +  useEffect(() => validate(), []);
Done

2022-08-05 23:34 UTC, stefcameron approved these changes

2022-08-05 23:38 UTC, merged