[PRODX-24162]: added tests for catalogEntities
Mirantis/lens-extension-cc pull request #1017
Opened 2022-08-08 23:27 UTC by AntonNos

<img width="721" alt="Screenshot 2022-08-09 at 02 26 04" src="https://user-images.githubusercontent.com/33761040/183531323-aed86bda-8b6a-40fc-bcc9-585efdf549be.png">

2022-08-08 23:31 UTC, stefcameron commented
👀

2022-08-08 23:45 UTC, stefcameron requested changes

2022-08-08 23:45 UTC, stefcameron commented on src/catalog/__tests__/catalogEntities.spec.js
> +import { CatalogEntity } from '../../../__mocks__/@k8slens/extensions';
We shouldn't just get stuff from this package. This package is meant to mock the real one. So we should import `Common` from `@k8slens/extensions` (since it gets auto-mocked), and then get `CatalogEntity` like we would in real code: `const { Catalog: { CatalogEntity } } = Common;`

2022-08-08 23:45 UTC, stefcameron commented on src/catalog/__tests__/catalogEntities.spec.js
> +    });
Looks like you could combine all this into a single loop with

```
    [
      apiKinds.RHEL_LICENSE,
      apiKinds.PROXY,
      apiKinds.PUBLIC_KEY,
      apiKinds.CLUSTER,
      ...Object.values(apiCredentialKinds),
    ].forEach((apiKind) => {
```

And then use the default case to test `if (Object.values(apiCredentialKinds).includes(apiKind))` and if not, throw an error (instead of silently doing nothing) about an unexpected kind we don't have a test for yet.

2022-08-08 23:45 UTC, stefcameron commented on src/catalog/__tests__/catalogEntities.spec.js
> +  });
I appreciate the tests, but `modelToString()` and `entityToString()` (and the internal `_itemToString()`) are meant to be used for debug logging. We don't need to write tests for them (and writing tests would make tweaking these take more time, which wouldn't be necessary for debug/logging code).

Instead of these tests, let's ignore those 3 functions by ignoring each function, like this:
```
export const entityToString = /* istanbul ignore next -- for debug/logging only */ function (entity) {
```

2022-08-11 13:09 UTC, AntonNos commented on src/catalog/__tests__/catalogEntities.spec.js
> +import { CatalogEntity } from '../../../__mocks__/@k8slens/extensions';
Fixed

2022-08-17 08:42 UTC, AntonNos commented on src/catalog/__tests__/catalogEntities.spec.js
> +    });
Makes sense, fixed

2022-08-17 08:45 UTC, AntonNos commented on src/catalog/__tests__/catalogEntities.spec.js
> +  });
Got it. Removed them from tests.

2022-08-17 19:59 UTC, stefcameron commented
👀

2022-08-17 20:10 UTC, stefcameron requested changes

2022-08-17 20:10 UTC, stefcameron commented on src/catalog/__tests__/catalogEntities.spec.js
> +            }
Shouldn't it be this?

```suggestion
            if (Object.values(apiCredentialKinds).includes(apiKind)) {
              expect(catalogEntities.generateEntityUrl(entity)).toEqual(url);
            } else {
              throw new Error(`Unexpected apiKind="${apiKind}": Test case may need to be enhanced to support it`);
            }
```

As it is, I don't think we're testing any of the credential kinds...

2022-08-17 20:10 UTC, stefcameron commented on src/catalog/__tests__/catalogEntities.spec.js
> +      it(`returns url for |${apiKind}| entity`, () => {
Could you add another small test case that checks that if given an entity with an unknown/unsupported kind, it just returns the basic `https://{host}/projects/{namespace}` URL? That would finish off the coverage for the `generateEntityUrl()` function.

2022-09-06 15:13 UTC, stefcameron commented
@AntonNos Should this PR be fixed and merged, or closed? It's for a ticket we have since marked as done.

2022-09-12 21:13 UTC, AntonNos commented
> @AntonNos Should this PR be fixed and merged, or closed? It's for a ticket we have since marked as done.

I fixed comments, check please

2022-09-12 21:31 UTC, stefcameron requested changes
Thanks for updating this old PR. I think every use of `toEqual()` in all tests here should actually be `toBe()`. Please try to remember to use `toBe()` _unless_ you're really deep-comparing objects/arrays, at which point use `toEqual()`. So start with `toBe()`, and if that doesn't work or doesn't fit the test case, then use `toEqual()`.

2022-09-12 21:31 UTC, stefcameron commented on src/catalog/__tests__/catalogEntities.spec.js
> +      );
I think this expectation should be `toBe(testModel)` rather than `toEqual(testModel)` because `toBe` is referential equality (`===`) whereas `toEqual` will do a deep-compare of the objects, and we're expecting this function to return an item from the list, not generate a new one with the same structure.

2022-09-12 23:35 UTC, AntonNos commented
> toBe

Okay, understand. Will use toBe() first in the future tests

2022-09-13 01:32 UTC, stefcameron approved these changes
Thank you! 😄

2022-09-13 09:35 UTC, merged