[PRODX-24168]: Added tests for topBarItems
Mirantis/lens-extension-cc pull request #1038
Opened 2022-08-25 21:26 UTC by AntonNos

<img width="526" alt="Screenshot 2022-08-26 at 00 19 27" src="https://user-images.githubusercontent.com/33761040/186771878-1d7b24c0-592f-44cb-ba9e-d393fe7e8a4c.png">
<img width="699" alt="Screenshot 2022-08-26 at 00 25 33" src="https://user-images.githubusercontent.com/33761040/186771883-306443c3-bd3f-4288-bcc9-0eb889500e70.png">
<img width="564" alt="Screenshot 2022-08-26 at 00 25 43" src="https://user-images.githubusercontent.com/33761040/186771886-6b392176-e13d-4433-973d-0a7e0dc5919f.png">

OnClick handler wasn't covered, because need to update mocks.

2022-08-25 21:50 UTC, stefcameron commented
> nClick handler wasn't covered, because need to update mocks.

Actually, you don't need to update the mocks in order to test the click handler.

2022-08-25 21:50 UTC, stefcameron commented
👀

2022-08-25 21:51 UTC, stefcameron requested changes
Can you think of how you can test that click handler?

2022-08-26 09:24 UTC, AntonNos commented
> Can you think of how you can test that click handler?

Yes, I already know how to do this. You are right, no need to update extension.js. My fault😉

2022-08-26 23:23 UTC, stefcameron requested changes

2022-08-26 23:23 UTC, stefcameron commented on src/renderer/__tests__/topBarItems.spec.js
> +      console.log(`Navigated to ${route}`);
This isn't how you test if a function gets call with Jest. You create a spy function instead, and you use that function as the handler. Then you check if the spy was called:

```
let extension;

beforeEach(() => {
  extension = {
    navigate: jest.fn(),
  };
});

...

it('gets called' , () => {
  render(<TopBarItem />);

  user.click('the thing');

  expect(extension.navigate).toHaveBeenCalledTimes(1);
  expect(extension.nativate.mock.calls[0][0]).toBe(expected-value-of-parameter-passed-to-function-inside-code);
});
```

2022-08-26 23:23 UTC, stefcameron commented on src/renderer/__tests__/topBarItems.spec.js
> +      topBarItems.generateTopBarItems(extension)[0].components.Item;
Should be in a `beforeEach()` so it's fresh for every test.

2022-08-26 23:23 UTC, stefcameron commented on src/renderer/__tests__/topBarItems.spec.js
> +  });
Put all this in its own `describe('First top bar item', () => ...)` block so it's obvious these tests are all related to that first top bar item in the list.

This is where you should have the `beforeEach()` that loads that first top bar item out of the list.

2022-08-29 08:58 UTC, AntonNos commented on src/renderer/__tests__/topBarItems.spec.js
> +      console.log(`Navigated to ${route}`);
Thanks! Will take into account.

2022-08-29 09:03 UTC, AntonNos commented on src/renderer/__tests__/topBarItems.spec.js
> +      topBarItems.generateTopBarItems(extension)[0].components.Item;
Done

2022-08-29 09:03 UTC, AntonNos commented on src/renderer/__tests__/topBarItems.spec.js
> +  });
Done

2022-08-29 18:50 UTC, stefcameron requested changes
Almost there, just one more tweak.

2022-08-29 18:50 UTC, stefcameron commented on src/renderer/__tests__/topBarItems.spec.js
> +        expect(topBarItems.generateTopBarItems(extension).length).toEqual(1);
This expectation should be in its own test, outside of the "First top bar item" block since it's generic to all/any top bar items that might exist. It's checking that there is exactly one top bar item that gets rendered. And then the "first top bar item" block proceeds to test that first item in the list.

2022-08-29 23:06 UTC, AntonNos commented on src/renderer/__tests__/topBarItems.spec.js
> +        expect(topBarItems.generateTopBarItems(extension).length).toEqual(1);
Fixed

2022-08-29 23:46 UTC, stefcameron approved these changes
Thank you!

2022-09-02 20:00 UTC, merged