[CCLEX-72]: added tests to ProviderStore
Mirantis/lens-extension-cc pull request #1051
Opened 2022-09-02 18:56 UTC by AntonNos

<img width="662" alt="Screenshot 2022-09-02 at 21 55 40" src="https://user-images.githubusercontent.com/33761040/188219550-77291b33-175d-4d98-a9af-05e4546eb70d.png">
<img width="591" alt="Screenshot 2022-09-02 at 21 55 59" src="https://user-images.githubusercontent.com/33761040/188219556-10359422-5b97-4216-9daa-75eee4005f3f.png">

2022-09-02 21:28 UTC, stefcameron commented
👀

2022-09-02 21:48 UTC, stefcameron requested changes
71.4% is too low... We want all 4 categories to be above 85%.

If that `|| undefined` branch is the only thing left, you should be able to write a simple test for that like
```javascript
pr.error = '';
expect(pr.store.error).toBeUndefined();
```

2022-09-02 21:48 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +  };
While you're declaring a `const`, it's an object, so technically it's not constant (as in immutable). If it was just a primitive like string, number, boolean, null, undefined, then it would be fine. But when it's an object (or an array), it's always safer to redefine it in a `beforeEach()` block so it's new for every test, just in case a test inadvertently/unexpectedly ends-up modifying it for some reason.

2022-09-02 21:48 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +    expect(pr.clone()).toMatchObject(defaultStoreObj);
This would be a stronger test if the store contained either an array or an object property, and then you checked that this property, in the clone, is equal to the property in the original using referential equality (`===`).

Note that for this, you'll need to make a test that creates a class that inherits from `ProviderStore` and overrides `makeNew()` in order to add a new property to the ProviderStore's `store` property. Don't forget to call `super.makeNew()`. See https://github.com/Mirantis/lens-extension-cc/blob/master/src/renderer/store/CloudProvider.js#L14 -- incidentally, looks like we have a bug in CloudProvider in that the `makeNew()` override is _not_ calling `super.makeNew()` like it should.

2022-09-02 21:48 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +    );
```suggestion
    expect(document.querySelector('.message')).toHaveTextContent(
      `${pr.error} ${noteOwner}`
    );
```

2022-09-02 21:48 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +  });
Same as the previous test: These would be stronger tests if you had a class that inherits from `ProviderStore` and you could also validate that the extended class' `makeNew()` was called as a result of calling `pr.reset()` in order to generate new values for the store properties. No need to mock the extended class' `makeNew()`. Just by creating the store, then altering the property that the extended class sets on the store to something other than its default value, and then calling `pr.reset()` should result in the store's value for that property to be back to its original value...

2022-09-02 21:48 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +  });
Same as the previous test: These would be stronger tests if you had a class that inherits from `ProviderStore` and you could also validate that the extended class' `makeNew()` was called as a result of calling `pr.reset()` in order to generate new values for the store properties. No need to mock the extended class' `makeNew()`. Just by creating the store, then altering the property that the extended class sets on the store to something other than its default value, and then calling `pr.reset()` should result in the store's value for that property to be back to its original value...

2022-09-06 14:01 UTC, AntonNos commented
> 71.4% is too low... We want all 4 categories to be above 85%.
> 
> If that `|| undefined` branch is the only thing left, you should be able to write a simple test for that like
> 
> ```js
> pr.error = '';
> expect(pr.store.error).toBeUndefined();
> ```

All comments are fixed.

2022-09-06 14:46 UTC, stefcameron requested changes

2022-09-06 14:46 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +        return {
Should be calling `super.makeNew()` here -- also need to fix this in CloudProvider.js since it it not -- and the object you return should add the `testProperty` to the object you got from super...

2022-09-06 14:46 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +      expect(tps.clone().testProperty).toEqual(storeObj.testProperty);
`toEqual()` does not compare using referential equality (`===`) -- that is, checking that the left and right sides are equal, not just in the same structure (i.e. two arrays with the same elements), but also as being the same objects in _memory_. You should use `toBe()` here. `toEqual()` is like `==` whereas `toBe()` is like `===`.

2022-09-06 14:46 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +          error: undefined,
These are provided by the base class. No need to have `makeNew()` at all in this case since you aren't adding any custom properties.

But to address my previous comment about these tests here, you should keep `makeNew()`, call the superclass, and then add an additional custom property -- like what you're doing in your `clone()` tests.

Then you should set that property to some new value (`pr.store.testProperty = [1, 2, 3]`), reset the store, and then validate that `pr.store.testProperty` is back to its original value of an empty array...

2022-09-07 20:04 UTC, AntonNos commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +        return {
> Should be calling `super.makeNew()` here -- also need to fix this in CloudProvider.js since it it not -- and the object you return should add the `testProperty` to the object you got from super...

All comments are fixed

2022-09-07 20:04 UTC, AntonNos commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +        return {
Fixed

2022-09-07 20:04 UTC, AntonNos commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +      expect(tps.clone().testProperty).toEqual(storeObj.testProperty);
Got it, fixed

2022-09-07 20:04 UTC, AntonNos commented
@stefcameron Comments are fixed, check please.

2022-09-07 22:46 UTC, stefcameron commented
👀

2022-09-07 22:54 UTC, stefcameron approved these changes
Thanks for fixing that issue in CloudProvider too.

I pointed out 2 last things, but I don't need to review again if you decide to make those changes. Provided it builds, you can merge it.

2022-09-07 22:54 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +      expect(tps.clone().testProperty).toBe(storeObj.testProperty);
Wouldn't this work, and be simpler?
```suggestion
      expect(tps.clone().testProperty).toBe(tps.store.testProperty);
```

2022-09-07 22:54 UTC, stefcameron commented on src/renderer/store/__tests__/ProviderStore.spec.js
> +      expect(tps.store.testProperty.length).toEqual(0);
The proper assertion here would be
```suggestion
      expect(tps.store.testProperty).toHaveLength(0);
```

2022-09-08 10:25 UTC, AntonNos commented
> Thanks for fixing that issue in CloudProvider too.
> 
> I pointed out 2 last things, but I don't need to review again if you decide to make those changes. Provided it builds, you can merge it.

Thanks! I fixed them and going to merge.

2022-09-08 10:25 UTC, merged