[CCLEX-165]: added last sync time stamp to entity details view
Mirantis/lens-extension-cc pull request #1092
Opened 2022-09-21 23:14 UTC by AntonNos

<img width="1792" alt="Screenshot 2022-09-22 at 02 13 52" src="https://user-images.githubusercontent.com/33761040/191626199-70c1152d-5860-4048-ae84-56d85caa3cb5.png">

2022-09-22 18:13 UTC, stefcameron commented
👀

2022-09-22 18:20 UTC, stefcameron requested changes
Looks great overall, nice work! Just some minor naming requests.

2022-09-22 18:20 UTC, stefcameron commented on src/api/types/Resource.js
> +    const syncedDate = new Date();
Since this is meant to be a _private_ member, could you rename it to `_syncedDate` to follow the pattern in other classes like SyncManager, DataCloud, Cloud, etc?

2022-09-22 18:20 UTC, stefcameron commented on src/renderer/catalogEntityDetails.js
> +const getDataValue = (date) => {
Did you meant to name it `getDateValue()`?

2022-09-22 18:20 UTC, stefcameron commented on src/strings.ts
> +          le: () => 'Lens Extension',
`le` is convenient, but not meaningful when reading the code elsewhere. 🙂 Maybe `lensExtension`?

2022-09-22 18:45 UTC, stefcameron requested changes

2022-09-22 18:45 UTC, stefcameron commented on src/renderer/catalogEntityDetails.js
> +  return `${dayjs(date).format('MMMM DD, YYYY')} (${dayjs(date).fromNow(
I think we should add the hours, minutes, seconds and reduce the full month name to the abbreviation (I think that will be `MMM` instead of `MMMM`). Right now, we get "September 22, 2022 (a few minutes ago)` which isn't precise enough.

2022-09-22 18:45 UTC, stefcameron commented on src/catalog/catalogEntities.js
> +    syncedAt: rtv.STRING,
Adding this is good, but I see now that it's causing a change to the schema, which is causing an exception in the SyncStore.js [right here](https://github.com/Mirantis/lens-extension-cc/blob/master/src/store/SyncStore.js#L112) when it loads existing data from sync-store.json when Lens starts, which is resulting in the loss of all previously-synced items in the catalog if the DataCloud is disconnected/offline on load.

Basically, if a customer installs a newer version of this extension with this change in it, and their clouds are disconnected or they're offline somewhere, they won't see any of their items in their catalog.

So we need to "upgrade" those entities in the sync-store.json on load before validating them to avoid this issue.

One way would be to make this property optional (i.e. `syncedAt: [rtv.OPTIONAL, rtv.STRING]`) but the side effects of that is that we have to code defensively everywhere we want to use this property, and in reality, it's not really an optional property.

We may have other cases like this in the future, so how do you think we could handle this? Let's discuss before you implement a solution.

2022-09-22 22:45 UTC, AntonNos commented on src/api/types/Resource.js
> +    const syncedDate = new Date();
Okay, will do that also in future tasks.

2022-09-22 22:45 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +const getDataValue = (date) => {
Yes, thank you! My fault with typo

2022-09-22 22:47 UTC, AntonNos commented on src/strings.ts
> +          le: () => 'Lens Extension',
Fixed

2022-09-22 22:52 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +  return `${dayjs(date).format('MMMM DD, YYYY')} (${dayjs(date).fromNow(
Added

2022-09-22 22:56 UTC, AntonNos commented on src/catalog/catalogEntities.js
> +    syncedAt: rtv.STRING,
Hmm, I thought, that it should be synced at least once, when we connect/sync cloud in Lens. So I thought, that we will always have `syncedAt` as a string with date.

2022-09-23 00:04 UTC, stefcameron commented on src/renderer/catalogEntityDetails.js
> +  return `${dayjs(date).format('MMM DD, YYYY, HH:mm:ss')} (${dayjs(
Is that 24-hour or 12-hour time? Should be 24-hour.

2022-09-23 00:06 UTC, stefcameron commented on src/catalog/catalogEntities.js
> +    syncedAt: rtv.STRING,
Not for an existing customer upgrading to a newer version of the extension. Do you think there's something we could do in `SyncStore.js`...?

Keep in mind, this type of enhancement likely won't be the last we'll make, and we may get customers upgrading from varying older versions of the extension (like `6 -> 6.1` or `6.3 -> 6.10`, for example).

2022-09-23 09:55 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +  return `${dayjs(date).format('MMM DD, YYYY, HH:mm:ss')} (${dayjs(
<img width="482" alt="Screenshot 2022-09-23 at 12 54 33" src="https://user-images.githubusercontent.com/33761040/191936276-d3860a78-8869-41d1-af86-3270854bb8eb.png">
 It's 24-hour time.

2022-09-23 10:16 UTC, AntonNos commented on src/catalog/catalogEntities.js
> +    syncedAt: rtv.STRING,
Maybe in `getDefaults()`, we can add `syncedAt` property to each entity with default value (empty string??)?

2022-09-23 15:02 UTC, stefcameron commented on src/catalog/catalogEntities.js
> +    syncedAt: rtv.STRING,
That's along the lines of what I was thinking as well. But putting it in `getDefaults()` wouldn't work. How would you know all the entities to create, for each individual customer's installation...?

So I think we should add a function, `upgradeEntities(store)`, that we call at [line 110](https://github.com/Mirantis/lens-extension-cc/blob/master/src/store/SyncStore.js#L110). It's job will be to __cautiously__ iterate (i.e. use tests like optional chaining and IF statements to prevent crashes) through the store and look for `syncedAt` properties. If it's undefined, it will add it.

This way, when line 112 executes, the schema will be valid, and we can rely on that property always existing.

And I think if we're adding the property, since we don't know when it was last synced, we should create it as `new Date(0)` (i.e. the 1970/1/1 epoch when the Date object begins) so it's obvious it's old and may be outdated.

2022-09-23 16:17 UTC, AntonNos commented on src/catalog/catalogEntities.js
> +    syncedAt: rtv.STRING,
Thank you, let me check it.

2022-09-26 13:12 UTC, AntonNos commented on src/catalog/catalogEntities.js
> +    syncedAt: rtv.STRING,
Added new upgradeEntities() method

2022-09-26 16:16 UTC, stefcameron commented on src/store/SyncStore.js
> +    return Object.values(store).map((entity) => {
No need to return the resulting array, right?

2022-09-26 16:22 UTC, stefcameron requested changes

2022-09-26 16:22 UTC, stefcameron commented on src/store/SyncStore.js
> +      });
Since we're pre-validation here, we need to be more careful so we don't just crash on startup if the shape of the store isn't exactly as we expect it to be. Also, the store is expected to be a map of entity type to __array__ of entities of that type... And for each entity, we don't know if it'll be defined, and if it'll have a `metadata` property that's an object (remember, `typeof null === 'object'` in JS) on which we can check for a property and set a property since we can't do that on a primitive.

Our goal here should be to try our best to add that `syncedAt` property, if it's not defined, such that the call to `rtv.check({ store }, ...)` will succeed.

2022-09-26 18:19 UTC, AntonNos commented on src/store/SyncStore.js
> +    return Object.values(store).map((entity) => {
Yes, you are right, thanks.

2022-09-26 20:14 UTC, AntonNos commented on src/store/SyncStore.js
> +      });
Thanks for comment, I fixed it.

2022-09-26 20:33 UTC, stefcameron commented on src/renderer/catalogEntityDetails.js
> +  return `${dayjs(date).format('MMM DD, YYYY, HH:mm:ss')} (${dayjs(
I think one more thing that would make this nicer is to check for `date.getTime() === 0` and use the string "Unknown" instead of generating the related date that's like 52.5 years ago now.

2022-09-26 22:45 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +  return `${dayjs(date).format('MMM DD, YYYY, HH:mm:ss')} (${dayjs(
Makes sense, fixed.

2022-09-26 23:30 UTC, stefcameron requested changes

2022-09-26 23:30 UTC, stefcameron commented on src/renderer/catalogEntityDetails.js
> +    : 'Unknown';
Please use a string from `strings.js`... 🙂  I think we can use our existing one: https://github.com/Mirantis/lens-extension-cc/blob/master/src/strings.ts#L222

2022-09-26 23:30 UTC, stefcameron commented on src/renderer/catalogEntityDetails.js
> +    ? `${dayjs(date).format('MMM DD, YYYY, HH:mm:ss')} (${dayjs(date).fromNow(
The logic is reversed: It will show "Unknown" for all cases _except_ when it's the JS epoch... Make sure you test it at least manually...

2022-09-26 23:37 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +    ? `${dayjs(date).format('MMM DD, YYYY, HH:mm:ss')} (${dayjs(date).fromNow(
Sorry for such mistakes, I'm already falling asleep at the computer. Going to fix them right now

2022-09-26 23:38 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +    : 'Unknown';
Right, thank you

2022-09-27 00:03 UTC, stefcameron requested changes
Go to bed! 🙂 You can finish this once you get some rest.

2022-09-27 00:03 UTC, stefcameron commented on src/renderer/catalogEntityDetails.js
> +  return date.getTime() === 0
This is better, but if you run this, it crashes... because what you're passing to `getDateValue()` is a __string__ (either `spec.createdAt` or `metadata.syncedAt`), not a `Date` object. The `daysjs()` function handles a string and converts it to a `Date` for you. I didn't see it myself, until I ran the code. So probably this function would be better/safer as:
```javascript
const getDateValue = (date) => {
  const dateObj = new Date(date);
  return dateObj.getTime() === 0 ? unknownValue() : `...`;
};
```

2022-09-27 11:21 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +  return date.getTime() === 0
You are right, thanks for solution! Fixed.

2022-09-27 14:57 UTC, stefcameron approved these changes
👍

2022-09-27 19:09 UTC, merged