[CCLEX-65]: added tests for apiUtil
Mirantis/lens-extension-cc pull request #1135
Opened 2022-10-17 10:23 UTC by AntonNos

<img width="676" alt="Screenshot 2022-10-17 at 13 22 56" src="https://user-images.githubusercontent.com/33761040/196153962-fe84e212-623c-4633-a7f3-0398888d4151.png">
<img width="745" alt="Screenshot 2022-10-17 at 13 23 25" src="https://user-images.githubusercontent.com/33761040/196154062-bb71657d-c8df-453b-b19f-9d860640f705.png">

2022-10-17 21:39 UTC, stefcameron commented
👀

2022-10-17 21:42 UTC, stefcameron commented
Thanks for your on these tests! What we're aiming for is 85% on all 4 aspects here:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/2855350/196289043-778bb0ca-3a51-4815-9092-4d6e283f78cc.png">

Statements and Lines are still below 85%. Can you write a test to go into the IF block at line 177?

2022-10-17 22:00 UTC, stefcameron requested changes

2022-10-17 22:00 UTC, stefcameron commented on src/api/__tests__/apiUtil.spec.js
> +    mockConsole(['log', 'info', 'warn', 'error']); // automatically restored after each test
I think in most other test modules, we don't mock `error` so that if there are errors, they aren't prevented from surfacing in the logs -- unless we're specifically testing that an error message is logged using `console.error()`, of course.

2022-10-17 22:00 UTC, stefcameron commented on src/api/__tests__/apiUtil.spec.js
> +      'eyqJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkI.eyJleHAiOjE2NjQyMjYwMjIsImlhdCI6MTY2NDIyNTcyMiwiYXV0aF90aW1lIjoxNjY0MTkwMDM2LCJqdGkiOiIwYmJhYzQ3Yi1hN2Q5LTQyZTEtYWYzMy05OTdhNTA5NTg3OTgiLCJpc3MiO
This must be a real JWT. Where did it come from? Just want to make sure you're not using an actual token for security reasons... You can use https://jwt.io/ to decode it by pasting it on the left hand side. And you can use the right hand side to edit it or create one with any content you want. So you should generate one with a payload like `{ foo: 123 }` and test at line 69 that you get an object with the expected property and value back from the method instead of just testing you get an object with some properties.

2022-10-17 22:00 UTC, stefcameron commented on src/api/__tests__/apiUtil.spec.js
> +      it('triggers an error when invalid resourse type', async () => {
Typo: "resourse" -> "resource"

2022-10-17 22:00 UTC, stefcameron commented on src/api/__tests__/apiUtil.spec.js
> +        expect(Object.keys(result)).toHaveLength(7);
In this case, we expect the request to succeed, so it would be a much stronger test to assert that the given payload looks like a success rather than error. The way you've done it so far, something could break causing an error to be returned and the test might continue to think that everything's working.

2022-10-25 09:35 UTC, AntonNos commented on src/api/__tests__/apiUtil.spec.js
> +    mockConsole(['log', 'info', 'warn', 'error']); // automatically restored after each test
<img width="541" alt="Screenshot 2022-10-25 at 12 34 11" src="https://user-images.githubusercontent.com/33761040/197738818-1b2bc007-8017-40c6-9d0a-d857a94d852a.png">
I mocked `error` here, because in one of the test, I expected to have that error in console, and it thrown using `logger.error`

2022-10-25 09:43 UTC, AntonNos commented on src/api/__tests__/apiUtil.spec.js
> +      'eyqJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkI.eyJleHAiOjE2NjQyMjYwMjIsImlhdCI6MTY2NDIyNTcyMiwiYXV0aF90aW1lIjoxNjY0MTkwMDM2LCJqdGkiOiIwYmJhYzQ3Yi1hN2Q5LTQyZTEtYWYzMy05OTdhNTA5NTg3OTgiLCJpc3MiO
Thanks for letting me know about https://jwt.io/! Will use it in future work (if need).
I fixed test.

2022-10-25 09:44 UTC, AntonNos commented on src/api/__tests__/apiUtil.spec.js
> +      it('triggers an error when invalid resourse type', async () => {
Fixed

2022-10-25 18:03 UTC, stefcameron commented
👀

2022-10-25 18:05 UTC, stefcameron commented
@AntonNos I went looking for updates based on your comments, but I don't see any. Did you forget to push your commit?

2022-10-25 18:13 UTC, AntonNos commented
> @AntonNos I went looking for updates based on your comments, but I don't see any. Did you forget to push your commit?

Yes, I didn't push it, because not all comments was fixed. I had changes on my PC and once all comments will be fixed - I will push update and will re-request review.

2022-11-01 02:53 UTC, stefcameron commented on src/api/__tests__/apiUtil.spec.js
> +    mockConsole(['log', 'info', 'warn', 'error']); // automatically restored after each test
The tests are looking great now, and I think you removed the expectation related to the error log, right? I don't see an `expect(console.error).toHaveBeenCalled()` anywhere (which is good). So can we remove 'error' from the list here like in the other test specs?

2022-11-01 02:56 UTC, stefcameron reviewed
Looks good, just wondering about that `mockConsole()` configuration (see earlier comment thread).

2022-11-01 10:21 UTC, AntonNos commented on src/api/__tests__/apiUtil.spec.js
> +    mockConsole(['log', 'info', 'warn', 'error']); // automatically restored after each test
I checked it 1 more time, and without mocking 'error', we received it in console (logger.error is in the code). So I added 1 more expectation to tests. Check please

2022-11-01 10:30 UTC, AntonNos commented on src/api/__tests__/apiUtil.spec.js
> +    mockConsole(['log', 'info', 'warn', 'error']); // automatically restored after each test
Hmm, with mocked error test with error expectation fails. I removed it from mockConsole.

2022-11-01 16:38 UTC, stefcameron approved these changes

2022-11-01 16:41 UTC, stefcameron commented on src/api/__tests__/apiUtil.spec.js
> +    mockConsole(['log', 'info', 'warn', 'error']); // automatically restored after each test
I don't see any test that has `expect(console.error)...` so I'm not sure what you mean. I see you removed "error" from `mockConsole()`, so AFAICT, we're good. 🙂

2022-11-01 19:43 UTC, merged