[CCLEX-172]: added Overview/Summary panel to Cluster page
Mirantis/lens-extension-cc pull request #1152
Opened 2022-10-24 23:10 UTC by AntonNos

**Management cluster Overview panel:**
<img width="1792" alt="Screenshot 2022-10-27 at 14 40 53" src="https://user-images.githubusercontent.com/33761040/198275070-f1dc431e-e971-47f5-9434-f36f79c4e599.png">

**Child cluster Overview panel:**
<img width="1792" alt="Screenshot 2022-10-27 at 14 40 16" src="https://user-images.githubusercontent.com/33761040/198275104-5f7aa800-2aef-4bc3-b7b5-972323081c91.png">

**Light mode:**
<img width="1792" alt="Screenshot 2022-11-01 at 16 11 40" src="https://user-images.githubusercontent.com/33761040/199253806-f9e05345-8174-4acb-9f82-1c41cbadfce2.png">

**FYI:** Tests for `ClusterOverviewPage` and `SummaryPanel` components wasn't written, because need to modify `extension.js` (we are using `clusterEntity` from `Renderer.Catalog.catalogEntities` in `ClusterOverviewPage` and `DrawerTitle`/`DrawerItem` components in `SummaryPanel`).

2022-10-27 16:35 UTC, stefcameron commented
👀

2022-10-27 17:06 UTC, stefcameron requested changes
Screenshots look good! In general, let's avoid using tables whenever possible. Flex containers are a great lightweight alternative and I think easier to work with and style.

- [x] Can you add screenshots of what this looks like in Light mode?

2022-10-27 17:06 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +        return <>{strings.catalog.entities.common.details.unknownValue()}</>;
I think in this module, we've already imported as just `unknownValue()`

2022-10-27 17:06 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +            </table>
Tables are generally awkward. Could you just use a flex container instead? Same for each other item below...

2022-11-01 14:13 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +            {provider}
Removed. It was added, because I saw that in Figma we had a string near icon.

2022-11-01 14:21 UTC, AntonNos commented on src/renderer/catalogEntityDetails.js
> +export const getDateValue = (date) => {
Makes sense. Done

2022-11-01 14:45 UTC, AntonNos commented on src/strings.ts
> +          proxies: (count) => (count > 1 ? 'Proxies' : 'Proxy'),
Got it. I didn't know that 0 is plural😄

2022-11-01 14:47 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +  const getProvider = (provider) => {
You are right! Moved it outside

2022-11-01 14:49 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +            : unknownValue()}
Yes, missed that

2022-11-01 14:50 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +        return <>{strings.catalog.entities.common.details.unknownValue()}</>;
Thanks, fixed.

2022-11-01 15:00 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +            </table>
Yes, sure! I forgot to get rid of them after changing tables to DrawerItem

2022-11-01 17:14 UTC, stefcameron commented on src/strings.ts
>      },
This is mostly (not all, but most) a duplicate of the labels for the `Catalog > Cluster > View details` panel strings here: https://github.com/Mirantis/lens-extension-cc/blob/master/src/strings.ts#L259-L282

Let's move lines 197 to 231 down past the existing `export const catalog: Dict = {` definition, and then refer to those strings like this:

```javascript
      summary: {
        title: () => 'Summary',
        clusterName: () => 'Cluster name',
        serverStatus: () => catalog.entities.common.details.props.serverStatus,
        syncTime: () => catalog.entities.common.details.props.lastSync,
        provider: () => catalog.entities.cluster.details.props.provider,
        managementCluster: catalog.entities.cluster.details.props.managementCluster,
        isManagementCluster: catalog.entities.cluster.details.props.isManagementCluster,
        releaseVersion: () => catalog.entities.cluster.details.props.release,
        namespace: () => 'Namespace',
        clusterUrl: () => 'Cluster URL',
        clusterObjects: {
          title: () => 'Cluster objects',
          credentials: (count) => (count === 1 ? 'Credential' : 'Credentials'),
          sshKeys: (count) => (count === 1 ? 'SSH key' : 'SSH keys'),
          rhelLicenses: (count) =>
            count === 1 ? 'RHEL license' : 'RHEL licenses',
          proxies: (count) => (count === 1 ? 'Proxy' : 'Proxies'),
        },
      },
```

You'll want to fill in the rest in your Details PR...

Also, instead of `mccStatus`, let's use `serverStatus` (trying to avoid using a marketing term in the name of a variable/property) (I renamed it above already).

Also, `syncTime` should be `lastSync` with label "Last sync" like we have in the View Details panel -- we should keep the same labels when possible. I fixed/updated it in the mock since it was "Sync time" there instead of "Last sync".

2022-11-01 17:14 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +const MccStatus = styled.p`
Can we name this `ServerStatus` instead? I'd like to avoid using marketing terms like `mcc` in variable names as much as possible.

2022-11-01 17:14 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +            : unknownValue()}
Still needs fixing as far as I can see in the code.

2022-11-01 17:23 UTC, stefcameron requested changes
Thanks for the Light theme screenshot. There seems to be some styling issue with the `<DrawerTitle>` component's background color that isn't switching with the theme here, but isn't present elsewhere in Lens. Notice how the background isn't visible in the Light theme, but it is in the Dark theme (I'm assuming that's because the background is there, and happens to match the Light theme's background gray color):

<img width="989" alt="image" src="https://user-images.githubusercontent.com/2855350/199296684-24c08079-be28-4d5c-8199-95d11073b050.png">

See how the `<DrawerTitle>` component behaves elsewhere (here in the `Catalog > Cluster > View Details` panel):

<img width="769" alt="image" src="https://user-images.githubusercontent.com/2855350/199296979-9334b21a-51a2-4be1-aa6b-435c0fd1f263.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2855350/199297500-53f4c234-5676-41a6-a988-fd775320a37e.png">

2022-11-01 17:23 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +              <span>{clusterEntity.metadata.labels['credential'] || '--'}</span>
Instead of hard coding the empty `"--"` string value, let's put it in the strings in `catalog.entities.common.details.emptyValue: () => '--'` like we have for `unknownValue()` so we can re-use it consistently across this, the Cluster Page Details panel, and also the Cluster View Details panel...

2022-11-01 17:23 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +const ProviderWrapper = styled.span(() => ({
Looks like you're using a `<span>` as a container, which isn't legal HTML. Seems like this should be a `<div>`.

2022-11-01 17:23 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +const EntityWrapper = styled.span(() => ({
Looks like you're using a `<span>` as a container, which isn't legal HTML. Seems like this should be a `<div>`.

2022-11-01 17:23 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +const IconWrapper = styled.span(() => ({
Looks like you're using a `<span>` as a container, which isn't legal HTML. Seems like this should be a `<div>`.

2022-11-01 19:45 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +            : unknownValue()}
Strange, I fixed that. Maybe missclicked ctrl+z or so. Sorry, fixed now

2022-11-01 21:26 UTC, AntonNos commented on src/strings.ts
>      },
Makes sense, fixed

2022-11-01 21:26 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +const MccStatus = styled.p`
Done

2022-11-01 23:35 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +              <span>{clusterEntity.metadata.labels['credential'] || '--'}</span>
Makes sense, done.

2022-11-01 23:36 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +const ProviderWrapper = styled.span(() => ({
Yes, I used span because it was a table before. Fixed now, thanks for comment

2022-11-02 01:51 UTC, stefcameron commented
As discussed in Slack, let's address the light theme issue in a separate PR.

2022-11-02 09:58 UTC, AntonNos commented
> 

Yes, I pushed update and will work on it in separate PR

2022-11-02 14:42 UTC, stefcameron requested changes
Nearly there! Just 3 small things that should be in #1174 instead of this PR since they're related to that fix, and the way they are here, it's not the right fix since it requires the page reload...

2022-11-02 14:42 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +    : darkTheme;
This should go in #1174...

2022-11-02 14:42 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +        <PanelTitle isLightMode={theme.mode === themeModes.LIGHT}>
This should go in #1174...

2022-11-02 14:42 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +`;
This should go in #1174...

2022-11-02 15:03 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +    : darkTheme;
Removed from current PR

2022-11-02 15:03 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +        <PanelTitle isLightMode={theme.mode === themeModes.LIGHT}>
Removed from current PR

2022-11-02 15:03 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +`;
Removed from current PR

2022-11-02 15:10 UTC, merged