[CCLEX-174]: Added status conditions panel to cluster Overview page
Mirantis/lens-extension-cc pull request #1158
Opened 2022-10-26 10:25 UTC by AntonNos

**Status conditions available (mocked ATM):**
<img width="1792" alt="Screenshot 2022-10-26 at 13 21 20" src="https://user-images.githubusercontent.com/33761040/198002625-d08b8e00-b431-416e-bae3-83ece51edd3c.png">

**Status conditions doesn't available:**
<img width="1792" alt="Screenshot 2022-10-26 at 13 20 10" src="https://user-images.githubusercontent.com/33761040/198002719-80ed6a51-eadf-477f-8c7c-d8800a45354c.png">

**Tests coverage:**
<img width="908" alt="Screenshot 2022-10-26 at 13 22 48" src="https://user-images.githubusercontent.com/33761040/198002753-cba7251b-6228-43c4-8991-adf02a4dcef8.png">

**FYI:** Tests for `ClusterOverviewPage` component wasn't written, because we are using `clusterEntity` from `Renderer.Catalog.catalogEntities`, but we decided not to change `extension.js` anymore.

2022-10-26 20:44 UTC, stefcameron commented
👀

2022-10-26 21:02 UTC, stefcameron requested changes
Thank you for your work on this!

2022-10-26 21:02 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanelContent.js
> +import propTypes from 'prop-types';
Could we rename this file to just `ClusterConditionsPanel`? I feel like the "Content" at the end isn't necessary and just making the file name that much longer.

2022-10-27 11:56 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanelContent.js
> +    isErrorState ? 'var(--colorError)' : 'var(--colorSuccess)'};
You are right, thanks. Fixed

2022-10-27 12:13 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanelContent.js
> +    width: calc(100% / 3);
Made responsive layout. Will attach new screenshots after updating PR.

2022-10-27 12:18 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanelContent.js
> +                <p>{truncate(condition.message, { length: 250 })}</p>
Fixed

2022-10-27 12:21 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanelContent.js
> +  conditions: propTypes.array.isRequired,
I agree with you, fixed

2022-10-27 12:42 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanelContent.js
> +          {conditions.map((condition) => (
Done

2022-10-27 13:12 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/__tests__/ClusterConditionsPanelContent.spec.js
> +      expect(screen.getByText(condition.type)).toBeInTheDocument();
You are right, done.

2022-10-27 13:14 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanelContent.js
> +import propTypes from 'prop-types';
I agree, done.

2022-10-27 17:20 UTC, stefcameron requested changes
Thanks for addressing my previous comments. Just need to refine how the layout behaves as we discussed in Figma and our meeting:

- Simple flex column wrap container.
- Min item width of 360px.
    - Thought was to allow them to stretch to fit so all columns are filled evenly, but this might not be possible with a flex container because we can't control how many columns are necessary and if the container's width allows for 4 columns, we should let the content reflow into 4 columns, so we may need to just pin the width to 360px.
- Fixed height of type value + 2 lines of message.
- If message is longer than X characters, truncate string with "..." and add a tooltip (Lens should have a Tooltip component we can use).
- Allow the container to scroll in both directions if necessary.

2022-10-27 17:22 UTC, stefcameron commented
Also, I see now there's duplicate code here (`ClusterOverviewPage`) with #1152 and #1161. This PR should've been based on #1152 and #1161 should've been based on #1152 also in order to avoid this... But this PR seems to have much less duplicated code with #1152 so you don't need to rebase it if you just want to deal with the inevitable merge conflicts. 🙂

2022-11-02 21:20 UTC, stefcameron commented
👀

2022-11-02 22:48 UTC, stefcameron approved these changes
This is good! Nice work on the conditions panel and the reactive layout (1-3 columns), it appears to work nicely in my testing.

2022-11-02 22:50 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanel.js
> +import propTypes from 'prop-types';
@AntonNos Actually, I figured I would just do this in https://github.com/Mirantis/lens-extension-cc/pull/1158/commits/542064346615a43f190355656e7c6d275335bd63 since I was in there already. Are you OK with this?

2022-11-02 22:52 UTC, stefcameron commented
@AntonNos While testing your changes locally, I discovered that we actually had no way of ever getting the conditions in the cluster entity because we weren't passing them from the cluster resource (that we get from the DataCloud's sync) into the cluster entity (that ends-up in the catalog, and which we end-up rendering in the cluster page). So I made the necessary hook ups in this commit: https://github.com/Mirantis/lens-extension-cc/pull/1158/commits/4204fda2735269dd83702964900ad79aabc534b8

If you're good with that, and my file renaming (see other comment above), then this PR is good to be merged.

2022-11-03 10:28 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ClusterConditionsPanel.js
> +import propTypes from 'prop-types';
Yes, sure! Thank you for helping with that!

2022-11-03 10:30 UTC, AntonNos commented
> @AntonNos While testing your changes locally, I discovered that we actually had no way of ever getting the conditions in the cluster entity because we weren't passing them from the cluster resource (that we get from the DataCloud's sync) into the cluster entity (that ends-up in the catalog, and which we end-up rendering in the cluster page). So I made the necessary hook ups in this commit: [4204fda](https://github.com/Mirantis/lens-extension-cc/commit/4204fda2735269dd83702964900ad79aabc534b8)
> 
> If you're good with that, and my file renaming (see other comment above), then this PR is good to be merged.

Thanks for helping!
Yes, we didn't have conditions, thats why I used mocked for testing. I'm completely good with your changes, so going to merge it.

2022-11-03 10:30 UTC, merged