WIP [CCLEX-176]: Details panel for Cluster page
Mirantis/lens-extension-cc pull request #1161
Opened 2022-10-27 10:58 UTC by AntonNos

![ezgif-3-bc4cc20330](https://user-images.githubusercontent.com/33761040/198266646-6185e4d3-3338-4e47-8621-9e26e8f3584e.gif)

### TODO
- [ ] Add tests for new components.

2022-10-27 17:07 UTC, stefcameron commented
👀

2022-10-27 17:09 UTC, stefcameron commented
Before I review this, could you please rebase it onto your Summary panel PR so that it only contains the changes necessary to add the Details panel? There are duplicate changes between the two PRs...

2022-11-03 17:21 UTC, AntonNos commented
> Looks like this branch/PR still needs more rebasing. I see SummaryPanel in here...
> 
> Also, some files to rename: `ClusterDetailsPage -> ClusterDetailsView`, `MccInformation -> ServerInformation`, `MirantisStacklightInformation -> LmaInformation` (Logging, Monitoring, Alerting) -- want to stay away from those marketing terms like "Mcc", "Mirantis", "StackLight" (other than in string values).

Rebased and fixed some moments with naming etc...
Ready for testing.

2022-11-03 17:25 UTC, AntonNos commented
> SummaryPanel

FYI: You see `SummaryPanel` here, because I moved `getProvider` method to ClusterPage helpers and made changes in  `SummaryPanel.js`.

2022-11-03 17:41 UTC, stefcameron commented
👁️

2022-11-03 18:09 UTC, stefcameron requested changes
I have to ask, what does it look like in Light mode? 😉

2022-11-03 18:09 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/ServerInformation.js
> +  const browserUrl = `${clusterEntity.metadata.cloudUrl}/projects/${clusterEntity.metadata.namespace}/clusters/${clusterEntity.metadata.name}`;
I feel like we already generate this link somewhere else, and we might have a utility function for it somewhere. Is that not the case?

2022-11-03 18:09 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/ServerInformation.js
> +          )}
No need for a conditional here. We will always have the cluster's URL.

2022-11-03 18:09 UTC, stefcameron commented on src/renderer/components/ClusterPage/helpers.js
> + * @returns {HTMLElement} Provider icon.
In reality, it returns a `ReactElement` (as in, something to render) because it could be either an actual element, or just a string.

Have you tested what happens when just a string is returned? Especially how the layout behaves? Wondering if we should be returning `<ProviderWrapper>{unknownValue()}</ProviderWrapper>` instead of just a string...

2022-11-03 18:09 UTC, stefcameron commented on src/renderer/components/ClusterPage/helpers.js
> +import styled from '@emotion/styled';
In keeping consistent with other files in the repo, could we name this `clusterPageUtil.js` instead of `helpers.js`?

2022-11-03 18:09 UTC, stefcameron commented on src/strings.ts
> +        clusterUrl: () => 'Cluster URL',
I thought we already had a `clusterUrl`... In the summary strings?

2022-11-03 18:09 UTC, stefcameron commented on src/strings.ts
> +        mkeDashboard: catalog.entities.cluster.details.props.dashboardUrl,
Can we stay consistent with the property name and call it `dashboardUrl` instead of `mkeDashboard`?

2022-11-03 18:09 UTC, stefcameron commented on src/strings.ts
> +      mirantisStacklight: {
Maybe `lmaInformation` now?

2022-11-03 18:09 UTC, stefcameron commented on src/strings.ts
> +      mirantisContainerCloud: {
Maybe `serverInformation` now?

2022-11-03 19:33 UTC, AntonNos commented on src/renderer/components/ClusterPage/Details/ClusterDetailsView.js
> +  DEV_ENV && rtv.verify(clusterEntity, clusterEntityModelTs);
Makes sense, done.

2022-11-03 19:39 UTC, AntonNos commented on src/renderer/components/ClusterPage/Details/ClusterDetailsView.js
> +      <LmaInformation lma={clusterEntity.spec.lma} />
Also fixed that in `ClusterOverviewView`

2022-11-03 22:58 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/ServerInformation.js
> +  const browserUrl = `${clusterEntity.metadata.cloudUrl}/projects/${clusterEntity.metadata.namespace}/clusters/${clusterEntity.metadata.name}`;
Yes, can we not use this? `import { generateEntityUrl } from '../catalog/catalogEntities';`

2022-11-04 19:38 UTC, stefcameron requested changes
Adding a comment to remind us that we need to add another row to the StackLight section which we now have in the View Details panel: https://github.com/Mirantis/lens-extension-cc/blob/master/src/renderer/catalogEntityDetails.js#L162-L168

2022-11-04 19:38 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/LmaInformation.js
> +      <DrawerItemsWrapper>
Adding a comment to remind us that we need to add another row to the StackLight section which we now have in the View Details panel: https://github.com/Mirantis/lens-extension-cc/blob/master/src/renderer/catalogEntityDetails.js#L162-L168

2022-11-06 22:55 UTC, AntonNos commented on src/renderer/components/ClusterPage/Details/ServerInformation.js
> +  const browserUrl = `${clusterEntity.metadata.cloudUrl}/projects/${clusterEntity.metadata.namespace}/clusters/${clusterEntity.metadata.name}`;
Yes, you are right! We can use `generateEntityUrl`.

2022-11-06 23:00 UTC, AntonNos commented on src/renderer/components/ClusterPage/helpers.js
> + * @returns {HTMLElement} Provider icon.
<img width="899" alt="Screenshot 2022-11-07 at 00 59 25" src="https://user-images.githubusercontent.com/33761040/200199946-cbc4be28-cdc5-4259-982e-2cb74f3b24c3.png">
It looks not bad for me with just a string. Let me know what you think.

2022-11-06 23:01 UTC, AntonNos commented on src/renderer/components/ClusterPage/helpers.js
> +import styled from '@emotion/styled';
Fixed

2022-11-06 23:07 UTC, AntonNos commented on src/strings.ts
> +        clusterUrl: () => 'Cluster URL',
Yes. I moved them to `clusterPage.common`.

2022-11-06 23:08 UTC, AntonNos commented on src/strings.ts
> +        mkeDashboard: catalog.entities.cluster.details.props.dashboardUrl,
Yes, sure. Fixed.

2022-11-06 23:10 UTC, AntonNos commented on src/strings.ts
> +      mirantisStacklight: {
Fixed

2022-11-06 23:10 UTC, AntonNos commented on src/strings.ts
> +      mirantisContainerCloud: {
Fixed

2022-11-06 23:32 UTC, AntonNos commented on src/renderer/components/ClusterPage/Details/LmaInformation.js
> +      <DrawerItemsWrapper>
Added new row.

2022-11-06 23:33 UTC, AntonNos commented
> 

Light mode screenshot attached.

2022-11-07 17:51 UTC, stefcameron commented
👀

2022-11-07 18:04 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/ConditionsPanel.js
> +          {clusterEntity.spec.conditions
On line 77, you're being defensive, but on line 79, you're being offensive. Would be better to extract the conditions into a local variable and then use the same one in both places:

```javascript
const conditions = clusterEntity.spec.conditions || [];
  return (
    <Container>
      {conditions.length > 0 ? (
        <ConditionsList>
          {conditions
```

2022-11-07 18:06 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/KubernetesInformation.js
> +}));
I'm starting to recognize this in a lot of the modules. Are these not two small components we can extract, define once under `/src/renderer/components/ClusterPage` and then reuse in all the `*View` components...?

2022-11-07 18:07 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/LmaInformation.js
> +}));
Yes, same thing here... Let's pull these 2 styled components out (here and in all other views) and reuse them.

2022-11-07 18:07 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/LmaInformation.js
> +}));
Probably this too can be reused in a few of the views instead of redefined multiple times.

2022-11-07 18:10 UTC, stefcameron commented on src/renderer/components/ClusterPage/Details/ServerInformation.js
> +}));
Identical 3 styled components again. 😄 Definitely need to extract these and reuse them.

2022-11-07 18:15 UTC, stefcameron commented on src/strings.ts
> +        title: () => 'Mirantis Container Cloud',
```suggestion
        title: () => mccFullName,
```

2022-11-08 14:10 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/ConditionsPanel.js
> +          {clusterEntity.spec.conditions
Thanks for tip! Fixed

2022-11-08 14:33 UTC, AntonNos commented on src/renderer/components/ClusterPage/Details/KubernetesInformation.js
> +}));
Makes sense, done.

2022-11-08 14:33 UTC, AntonNos commented on src/renderer/components/ClusterPage/Details/LmaInformation.js
> +}));
Done

2022-11-08 14:33 UTC, AntonNos commented on src/renderer/components/ClusterPage/Details/ServerInformation.js
> +}));
Done

2022-11-08 14:37 UTC, AntonNos commented on src/strings.ts
> +        title: () => 'Mirantis Container Cloud',
Fixed

2022-11-08 18:42 UTC, stefcameron commented
@AntonNos These `Merge branch 'master' into CCLEX-176__Cluster-page__Details-panel` merges are also messing up review history. If you could refrain from ever updating a branch with code from master _unless absolutely necessary_ until the PR is reviewed and approved, that would be great! Otherwise, every time you rebase or merge from master, all review history is lost and I have to start over...

2022-11-08 18:49 UTC, stefcameron requested changes
Just one more thing and we're done!

2022-11-08 18:49 UTC, stefcameron commented on src/renderer/components/ClusterPage/ClusterPage.js
> +}));
It's a bit strange having these in the ClusterPage and then having what are technically the children of the ClusterPage importing from their parent. That's borderline a circular dependency...

How about we move these into `clusterPageUtil.js`, or make a new `clusterPageComponents.js` module as a sibling to `clusterPageUtil.js` and `ClusterPage.js`?

2022-11-08 20:39 UTC, AntonNos commented
> @AntonNos These `Merge branch 'master' into CCLEX-176__Cluster-page__Details-panel` merges are also messing up review history. If you could refrain from ever updating a branch with code from master _unless absolutely necessary_ until the PR is reviewed and approved, that would be great! Otherwise, every time you rebase or merge from master, all review history is lost and I have to start over...

Sorry for that, I just clicked "Update branch "button  here in github. Will do that after review in the future.

2022-11-08 20:48 UTC, AntonNos commented on src/renderer/components/ClusterPage/ClusterPage.js
> +}));
Makes sense. I think new `clusterPageComponents.js` module will be more logical for styled components rather then putting them in `clusterPageUtil.js`.

2022-11-08 20:50 UTC, stefcameron commented
> > @AntonNos These `Merge branch 'master' into CCLEX-176__Cluster-page__Details-panel` merges are also messing up review history. If you could refrain from ever updating a branch with code from master _unless absolutely necessary_ until the PR is reviewed and approved, that would be great! Otherwise, every time you rebase or merge from master, all review history is lost and I have to start over...
> 
> Sorry for that, I just clicked "Update branch "button here in github. Will do that after review in the future.

Should the styled components in `clusterPageUtil.js` also move into `clusterPageComponents.js`?

2022-11-08 20:50 UTC, stefcameron commented on src/renderer/components/ClusterPage/ClusterPage.js
> +}));
Should the styled components in clusterPageUtil.js also move into clusterPageComponents.js?

2022-11-08 21:05 UTC, AntonNos commented on src/renderer/components/ClusterPage/ClusterPage.js
> +}));
I don't think so, because in `clusterPageUtil.js` we have only 2 stiled components, and both of them are related to `getProvider`, which is in `clusterPageUtil.js`.

2022-11-08 23:02 UTC, stefcameron approved these changes
👍

2022-11-08 23:06 UTC, stefcameron commented
<img width="885" alt="image" src="https://user-images.githubusercontent.com/2855350/200694838-9c5f78c1-c541-48c1-b691-253833b4992c.png">

FYI, I'm not sure what happened here, but whatever you did when you made that final update to this branch involved another rebase, which meant I had to re-review _everything_ one more time. 🙂 

When you're working on a branch, do not update it from master. Just keep making additional commits on top of the previous ones locally and then `git push origin HEAD:<branch-name>`. That's it. That will add an incremental commit to the branch/PR and I'll be able to see the diff in the review. Once the PR is approved, then you can rebase it onto master -- if need be (not necessary if there are no conflicts). Finally, you "squash & merge" everything as a single commit into master.

2022-11-09 00:19 UTC, AntonNos commented
> <img alt="image" width="885" src="https://user-images.githubusercontent.com/2855350/200694838-9c5f78c1-c541-48c1-b691-253833b4992c.png">
> 
> FYI, I'm not sure what happened here, but whatever you did when you made that final update to this branch involved another rebase, which meant I had to re-review _everything_ one more time. 🙂
> 
> When you're working on a branch, do not update it from master. Just keep making additional commits on top of the previous ones locally and then `git push origin HEAD:<branch-name>`. That's it. That will add an incremental commit to the branch/PR and I'll be able to see the diff in the review. Once the PR is approved, then you can rebase it onto master -- if need be (not necessary if there are no conflicts). Finally, you "squash & merge" everything as a single commit into master.

Understand, thank you for explanation! Will do that in the future PRs.

2022-11-09 00:22 UTC, merged