Theme provider for cluster page
Mirantis/lens-extension-cc pull request #1174
Opened 2022-11-02 12:47 UTC by AntonNos

2022-11-02 19:25 UTC, stefcameron commented
👀

2022-11-02 21:19 UTC, stefcameron requested changes
Good start, but I think we need to organize things a bit more, and need to make sure we're using Emotion correctly...

2022-11-02 21:19 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +  const { theme } = useThemeSwitching();
At this level, you should be using `useTheme()` not this hook.

We need a new `ClusterPage.js` in the src/renderer/components/ClusterPage directory that is like the GlobalPage is now except that it has a `children: propTypes.node.isRequired` prop that requires a single child, which it then renders inside a `<ThemeProvider>`.

Then in the `renderer.tsx` where we have this:

```javascript
    {
      id: ROUTE_CLUSTER_OVERVIEW,
      components: {
        Page: () => <ClusterOverviewPage />,
      },
    },
```

Change it to this:

```javascript
    {
      id: ROUTE_CLUSTER_OVERVIEW,
      components: {
        Page: () => <ClusterPage><ClusterOverviewView /></ClusterPage>,
      },
    },
```

Would be good to then rename `ClusterOverviewPage` to `ClusterOverviewView` (and then `ClusterEventsView`, `ClusterDetailsView` also) so that we put a view _into_ the cluster page...

Finally, here in SummaryPanel, you don't need to get the theme here. You can get it in the PanelTitle styled component itself and do the right thing there:

```javascript
const PanelTitle = styled(DrawerTitle)(({ theme }) => ({
  backgroundColor: theme.mode === themeModes.LIGHT ? something : undefined,
  ...
}));
```

2022-11-03 12:29 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +  const { theme } = useThemeSwitching();
Understand, thank you! Fixed

2022-11-03 13:45 UTC, AntonNos commented on src/renderer/components/useThemeSwitching.js
> +export const useThemeSwitching = () => {
Done

2022-11-03 15:30 UTC, stefcameron requested changes
Just two more improvements. Rest is looking great, and nice job on the additional tests!

2022-11-03 15:30 UTC, stefcameron commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +}));
Now that this still be the same thing in all views, let's pull it out to a separate little component in /src/renderer/components/ClusterPage and import it here as well as in the conditions view and details view...

2022-11-03 15:30 UTC, stefcameron commented on src/renderer/components/useThemeSwitching.js
> + * @returns {object} Object with theme mode.
Would be clearer as `@returns {{ theme: Object }} Object with a `theme` property that is the theme object to be used by the ThemeProvider.`

2022-11-03 16:46 UTC, AntonNos commented on src/renderer/components/useThemeSwitching.js
> + * @returns {object} Object with theme mode.
Thank you, fixed!

2022-11-03 17:00 UTC, AntonNos commented on src/renderer/components/ClusterPage/Overview/SummaryPanel.js
> +}));
Makes sense, done.

2022-11-03 17:03 UTC, stefcameron approved these changes
👍

2022-11-03 17:04 UTC, merged