WIP [CCLEX-175]: added events page
Mirantis/lens-extension-cc pull request #1206
Opened 2022-11-28 16:42 UTC by AntonNos

2022-12-05 17:49 UTC, stefcameron commented
👀

2022-12-05 19:09 UTC, stefcameron requested changes
Nice work! There are a lot of comments, but most of them are hopefully simple variable renamings for make the code clearer, especially when coming back to it for some reason in a few months or a year and not remembering how it all works...

Also, what does it look like the Light theme?

2022-12-06 10:32 UTC, john-papadami commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +}));
> 
I think it looks better as a white link, not intrusive, and uses to text to go along with the message "No items found". But does this clear the search field or clears the search filter and sets sources dropdown to "All sources"? In any case I probably would name it "Reset search" since the input field says search events and should perform the latter.

2022-12-06 11:56 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +}));
Yes, I got this styles from similar table in Lens (Cluster page -> Events).
<img width="1254" alt="Screenshot 2022-12-06 at 13 52 12" src="https://user-images.githubusercontent.com/33761040/205904412-dc6db06c-139b-4a9f-9c7d-78511f10e339.png">

But yes @john-papadami , you are right. I checked behaviour of that in Lens table, and it clears only search. It's actually naming of that button caused me a misunderstanding with the functional. So yes, it would be better to rename it.
So should I keep current styles for it?

2022-12-06 13:22 UTC, john-papadami commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +}));
@AntonNos Yes, let's keep the current style.

2022-12-06 13:31 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +        if (typeof singleItem[key] === 'object') {
Makes sense , fixed. BTW, I added light theme screenshot to description.

2022-12-06 13:39 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +  const [searchIndex, setSearchIndex] = useState([]);
Thanks, fixed

2022-12-06 13:41 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +        return { allValues: allValues.toString() };
Makes sense , fixed.

2022-12-06 13:41 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +            .indexOf(searchQuery.toLowerCase()) >= 0
Fixed

2022-12-06 13:46 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> + * @param {Array} data Origin data to filter.
Yes, sure. It sounds better. Fixed

2022-12-06 13:51 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +  const [origData, setOrigData] = useState([]);
You are right, it works without it. I added it to have origin object, but yes, we already have it in parameters.🤷‍♂️
Fixed

2022-12-06 13:54 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +  const [searchedData, setSearchedData] = useState([]);
Fixed

2022-12-06 13:56 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> + * @param {string} searchQuery Search query.
Sounds better. Fixed

2022-12-06 13:57 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +      setSearchedData(origData);
Fixed

2022-12-06 14:44 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/useTableSearch.js
> +  return { searchedData };
Fixed

2022-12-06 14:48 UTC, AntonNos commented on src/strings.ts
> +        emptyList: () => 'Item list is empty',
Fixed

2022-12-06 14:48 UTC, AntonNos commented on src/strings.ts
> +        noItemsFound: () => 'No items found.',
Fixed

2022-12-06 14:53 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/__tests__/useTableSearch.spec.js
> +    data: mockedData,
Fixed

2022-12-06 14:54 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +  events: propTypes.array.isRequired,
Fixed

2022-12-06 15:22 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +  handleResetFilters: propTypes.func.isRequired,
Thanks, will tale into account. Fixed

2022-12-06 16:25 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +}));
Fixed

2022-12-06 16:28 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +};
We have a bit different format in Figma, thats why I added new internal `formatDate`.
`4 days ago (2022-12-02, 20:31:18)` -> `2022-11-27, 17:37:30`.
If we can use date format like in other tabs, I will change it. 
What do you think? @stefcameron @john-papadami . Can we use this variant (`4 days ago (2022-12-02, 20:31:18)`)?

2022-12-06 17:51 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +};
Actually, if we've already decided to use one format, let's keep it. I'll fix it in the future if it doesn't fit

2022-12-06 17:56 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +};
Actually, if we've already decided to use one format, let's keep it. I'll fix it in the future if it doesn't fit

2022-12-06 18:01 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +            onClick={() => handleSync()}
Moved it outside of component

2022-12-06 18:37 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +  };
Done

2022-12-06 18:45 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +  };
Fixed for `handleSelectChange`, `handleSearchChange`, `handleSortChange` and `handleResetFilters`, but not for `handleSync`, because I moved it outside of component.

2022-12-06 18:48 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +  const [status, setStatus] = useState(clouds[cloudUrl].status);
Yes, sure. Done

2022-12-06 18:48 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +    data: events,
Done

2022-12-06 19:07 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +  const [modifiedEvents, setModifiedEvents] = useState([]);
Fixed

2022-12-06 20:05 UTC, stefcameron commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +  events: propTypes.array.isRequired,
`modifiedEvents` should just be an array containing a subset of items from `clusterEntity.spec.events`. Oooh, but those items aren't `ResourceEvent` instance anymore: They've been converted to plain objects. My bad on that one. So `propTypes.arrayOf(propTypes.object)` is probably enough in this case.

2022-12-06 20:11 UTC, stefcameron commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +};
Just add a parameter to `rendererUtil.formatDate(date, includeRelative = true)` and then call `rendererUtil.formatDate(date, false)` from here to produce just the `'YYYY-MM-DD, HH:mm:ss'` part.

2022-12-06 20:13 UTC, stefcameron commented on src/renderer/components/ClusterPage/Events/EventsTable.js
> +};
(I'm sorry I didn't realize there was indeed a slight difference. But I think adding a parameter is better than creating another function because the `'YYYY-MM-DD, HH:mm:ss'` is the same between the two, and how we want to print an exact date).

I think if we show a relative date in the future, it should be in a separate column with a heading like "Age".

2022-12-06 20:18 UTC, stefcameron requested changes
Thank you for working through all my previous comments. I appreciate it! Just a few more...

2022-12-06 20:18 UTC, stefcameron commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +            onClick={() => handleSync(clusterEntity.metadata.cloudUrl)}
This is still generating a new handler function on every render...

2022-12-06 20:25 UTC, stefcameron commented on src/renderer/components/ClusterPage/useTableSearch.js
> +        } else {
We also need to convert date objects using `rendererUtil.formatDate(date, false)` in the same way we display it because that's what the user sees and may search on.

2022-12-06 20:28 UTC, stefcameron commented
Thanks for posting the light theme screen shot. Why are there blue lines above and below the table header, only in light mode?

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/2855350/206015931-c4e0ee4c-4531-4fe6-8888-8aa74511b1c6.png">

2022-12-06 20:30 UTC, stefcameron commented
There's strange behavior when sorting columns: Even when a column has identical values on all visible rows, the search order still changes (can't tell exactly based on what; maybe it's the date?) when I toggle asc vs desc. If all the values are the same, once the column has been sorted once (i.e. when it wasn't the primary sort), shouldn't it remain the same afterward?

![lex-cluster-events-panel](https://user-images.githubusercontent.com/2855350/206016417-7fe3b55f-d94f-45e9-818a-f507050cab86.gif)

2022-12-08 10:51 UTC, AntonNos commented on src/renderer/components/ClusterPage/useTableSearch.js
> + * @returns {Array} Filtered data.
Fixed

2022-12-08 11:00 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +            onClick={() => handleSync(clusterEntity.metadata.cloudUrl)}
Fixed

2022-12-08 11:06 UTC, AntonNos commented
> There's strange behavior when sorting columns: Even when a column has identical values on all visible rows, the search order still changes (can't tell exactly based on what; maybe it's the date?) when I toggle asc vs desc. If all the values are the same, once the column has been sorted once (i.e. when it wasn't the primary sort), shouldn't it remain the same afterward?

Fixed. It was because of this `filters.sort.isAsc ? sortedEvents : sortedEvents.reverse()`. I changed login and made it without `reverse()`

2022-12-08 12:50 UTC, AntonNos commented on src/renderer/components/ClusterPage/useTableSearch.js
> +        } else {
<img width="1792" alt="Screenshot 2022-12-08 at 14 48 08" src="https://user-images.githubusercontent.com/33761040/206450788-1f9d3297-afcc-4727-b408-8965e594531d.png">
<img width="1792" alt="Screenshot 2022-12-08 at 14 48 44" src="https://user-images.githubusercontent.com/33761040/206450775-624ba3dc-0085-44e2-9416-c4595a94a424.png">

2022-12-08 12:50 UTC, AntonNos commented on src/renderer/components/ClusterPage/useTableSearch.js
> +        } else {
Without `!Array.isArray(singleItem[key])` is works well (I mean we don't have [object Object] in string). It converting all objects and arrays to strings with it values. I added some screenshots from JSbin where is a case that you expected.

2022-12-08 16:00 UTC, stefcameron commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +    // );
Can be removed?

2022-12-08 16:00 UTC, stefcameron commented on src/renderer/rendererUtil.js
> +export const formatDate = (date, includeRelative = true) => {
New parameter should be added to JSDoc

2022-12-08 16:00 UTC, stefcameron commented on src/renderer/components/ClusterPage/useTableSearch.js
> + * @param {string} str Unfiltered list of items to search.
Is it really a __list__? Looks more like a piece of text to check for a date. 🤔

2022-12-08 16:00 UTC, stefcameron commented on src/renderer/components/ClusterPage/useTableSearch.js
> +        } else {
If think the array case just happens to kind of work because you're using a `for..in` loop to iterate properties of objects, and `typeof [] === 'object'`. So without the `!Array.isArray()` check, you determine the array is an object and you recurse, at which point you iterate its elements.

But the problem with `for..in` is that it it iterates over all enumerable properties of an object -- including those inherited via the prototype chain. I'm surprised more stuff isn't coming out than it is.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#array_iteration_and_for...in

And since this function's purpose is to traverse a generic object without knowing its structure, it should be safely iterating over nested objects and arrays.

2022-12-08 16:00 UTC, stefcameron commented on src/renderer/components/ClusterPage/useTableSearch.js
> +                ? formatDate(singleItem[key], false)
Could you add a short comment here stating that we're formatting in the same we assume dates are displayed so as to search text as the user see's it in the table? That would help clarify why we're doing this special case.

2022-12-08 16:14 UTC, AntonNos commented on src/renderer/components/ClusterPage/useTableSearch.js
> + * @param {string} str Unfiltered list of items to search.
Ohh, sorry, copied JSDoc from `useTableSearch`, but forgot to change parameter description.

2022-12-08 16:15 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +    // );
Yes, done. Thanks

2022-12-08 16:19 UTC, AntonNos commented on src/renderer/rendererUtil.js
> +export const formatDate = (date, includeRelative = true) => {
Done

2022-12-08 16:25 UTC, AntonNos commented on src/renderer/components/ClusterPage/useTableSearch.js
> +                ? formatDate(singleItem[key], false)
Yes, sure, done.

2022-12-08 18:51 UTC, AntonNos commented on src/renderer/components/ClusterPage/useTableSearch.js
> +        } else {
Fixed it in way, that we discussed in Slack

2022-12-08 19:55 UTC, stefcameron approved these changes
I think it's good to go! I tested it locally and it works really well. Thank you for your work on this! 🙂

2022-12-08 20:11 UTC, merged