[CCLEX-185]: History panel
Mirantis/lens-extension-cc pull request #1224
Opened 2022-12-12 11:50 UTC by AntonNos

`EventsTable` and `HistoryTable` components were moved to re-usable `ItemsTable` component. Also did some changes in `EventsPanel` to meet `ItemsTable` structure.

### **Mocked data to see, how statuses are looking:**
<img width="1792" alt="Screenshot 2022-12-11 at 23 15 52" src="https://user-images.githubusercontent.com/33761040/207037648-d9d19f7f-d8d9-44b9-b2cd-d049f032a43c.png">

### **Real data:**
<img width="1792" alt="Screenshot 2022-12-12 at 03 04 38" src="https://user-images.githubusercontent.com/33761040/207037691-54f70322-121c-46f3-9692-f9d14db4abec.png">

2022-12-12 16:19 UTC, stefcameron requested changes
Nice work reusing the ItemsTable!

2022-12-12 16:19 UTC, stefcameron commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
> +};
I know `map()` iterates, but you're really just iterating the lists without transforming them. Using `forEach()` in both cases would be more accurate and make the code easier to understand.

But I suggest you use `flatMap()` to "map" the `history` array to an array of items. I also think you should rename the `history` parameter to `updates` because at the point the `updates` list is received, it's an `Array<ResourceUpdate>` -- it's not what you call "history" items yet. That's the _output_ of this function.

```javascript
return updates.flatMap((update) =>
  update.spec.stages.map((stage) => ({
    status: stage.status,
    timeAt: stage.timeAt,
    name: stage.name,
    message: stage.message,
    targetKind: update.spec.targetKind,
    targetName: update.spec.targetName,
    fromRelease: update.spec.fromRelease,
    release: update.spec.release,
  })));
```

I think the above is a lot more clear on what a "history" object is (a mix of stage and related update data). WDYT?

The types in the JSDoc should also be clarified:

```
 * @param {Array<ResourceUpdate>} updates List of resource updates.
 * @returns {Array<{ status: string, timeAt: string, name: string, message: string, targetKind: string, targetName: string, fromRelease: string|null, release: string }>} List of history objects.
```

Also renaming the function to `getHistory = (updates) => ...` would make the code more clear since this function is transforming a list of resource updates into a list of history.

2022-12-12 16:19 UTC, stefcameron commented on src/renderer/components/ClusterPage/ItemsTable.js
> +  '&&&': {
Triple `&&&`? I believe just a single `&` will suffice.

2022-12-12 16:19 UTC, stefcameron commented on src/renderer/components/ClusterPage/ItemsTable.js
> +                }}
It's a bit strange to be setting a `style` on a styled component. Why not pass the `singleItem` to the `TableCellWithPadding` and have it do this internally when it sets the color style?

2022-12-12 16:19 UTC, stefcameron commented on src/renderer/components/ClusterPage/ItemsTable.js
> +  items: propTypes.arrayOf(propTypes.array),
Can you use `propTypes.arrayOf(propTypes.shape({ ... }))` and explicitly describe what those items look like? That will be really helpful in the future when coming back to this code.

2022-12-12 16:19 UTC, stefcameron commented on src/renderer/components/ClusterPage/clusterPageComponents.js
> +`;
Since there are many props expected, it would be better to use the object for instead of the template string form so that the expected props can be easier to see:

```javascript
export const TableSyncButton = styled.button(({ isDisabled, isCloudFetching }) => ({ ... }));
```

2022-12-12 16:19 UTC, stefcameron commented on src/renderer/components/ClusterPage/clusterPageUtil.js
> +};
This feels like something the `useCloudSync()` hook should return. Feels a bit strange having this be here, separate from the hook.

2022-12-12 23:21 UTC, AntonNos commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
> + * @returns {{ Array }} array with arrays of objects.
Fixed

2022-12-12 23:26 UTC, AntonNos commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
> +};
You are right, it looks much cleaner. Thank you. Fixed

2022-12-12 23:29 UTC, AntonNos commented on src/renderer/components/ClusterPage/ItemsTable.js
> +  '&&&': {
Yes, I used triple `&&&` here, because I need to override styles with higher specificity. According to docs, need to use triple ampersands. It doesn't work with single one. Here is docs - https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity.

2022-12-12 23:33 UTC, AntonNos commented on src/renderer/components/ClusterPage/ItemsTable.js
> +                }}
Right, thank you. Fixed

2022-12-12 23:41 UTC, AntonNos commented on src/renderer/components/ClusterPage/ItemsTable.js
> +  items: propTypes.arrayOf(propTypes.array),
Done

2022-12-13 00:00 UTC, AntonNos commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
> +};
Fixed

2022-12-13 00:05 UTC, AntonNos commented on src/renderer/components/ClusterPage/clusterPageComponents.js
> +`;
Makes sense, fixed

2022-12-13 00:13 UTC, AntonNos commented on src/renderer/components/ClusterPage/clusterPageUtil.js
> +};
You are right! I don't know why I placed it outside of hook🤷‍♂️
Thanks for tip

2022-12-13 01:08 UTC, stefcameron reviewed
Looking good! Just a couple more small things.

2022-12-13 01:08 UTC, stefcameron commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
>        return 'var(--colorError)';
Is it really necessary to lowercase everything? The `status` is supposed to be a specific string we can count on. I think we can drop the lowercasing.

2022-12-13 01:08 UTC, stefcameron commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
> +            onClick={() => syncCloud()}
Same here, we've lost the cached callback...

2022-12-13 01:08 UTC, stefcameron commented on src/renderer/components/ClusterPage/useCloudSync.js
> +  const syncCloud = () => {
Since this is in a hook, I believe it's legal to do this:
```suggestion
  const handleSyncCloud = useCallback(() => {...}, cloudUrl);
```

And then return `handleSyncCloud` as the handler to use.

2022-12-13 01:08 UTC, stefcameron commented on src/renderer/components/ClusterPage/ItemsTable.js
> +  '&&&': {
Huh, that's cool. I didn't know about this. Thanks!

2022-12-13 13:22 UTC, AntonNos commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
>        return 'var(--colorError)';
You are right, we can remove it. Fixed

2022-12-13 13:27 UTC, AntonNos commented on src/renderer/components/ClusterPage/useCloudSync.js
> +  const syncCloud = () => {
Good idea, done.

2022-12-13 13:27 UTC, AntonNos commented on src/renderer/components/ClusterPage/History/HistoryPanel.js
> +            onClick={() => syncCloud()}
Fixed

2022-12-13 13:27 UTC, AntonNos commented on src/renderer/components/ClusterPage/Events/EventsPanel.js
> +            onClick={() => syncCloud()}
Fixed

2022-12-13 18:03 UTC, stefcameron commented on src/renderer/components/ClusterPage/useCloudSync.js
> +    syncCloud(cloudUrl);
I'm surprised the ESLint "rules of hooks" _exhaustive dependencies_ rule isn't flagging this as a missing dependency in the `useCallback`'s dependency list because as it's currently setup, the callback will change only when `cloudUrl` changes, yet the callback calls an ever-changing `syncCloud()` function (unnecessarily changes on every render when the hook is called).

`syncCloud()` is just one line and not called from anywhere else. I suggest either getting rid of it and having the `IpcRenderer` call right here, or moving the `syncCloud()` function _outside_ the `useCloudSync` hook.

2022-12-13 18:24 UTC, AntonNos commented on src/renderer/components/ClusterPage/useCloudSync.js
> +    syncCloud(cloudUrl);
I moved `IpcRenderer` call inside `useCallback` and get rid of `syncCloud`.

2022-12-13 18:35 UTC, stefcameron commented
@AntonNos Thanks for addressing all my comments! Just one last thing about the layout:

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/2855350/207416456-6c54b25c-7054-40b6-a2d4-1ccde17545e5.png">

I think we need to give more room for the Name column. I'm thinking equal "weight" in the flex layout as we give to the Message, because the Message is only used for details. Otherwise, they use the Name as the main description of the history update.

2022-12-13 19:24 UTC, AntonNos commented
> @AntonNos Thanks for addressing all my comments! Just one last thing about the layout:
> 
> <img alt="image" width="1203" src="https://user-images.githubusercontent.com/2855350/207416456-6c54b25c-7054-40b6-a2d4-1ccde17545e5.png">
> 
> I think we need to give more room for the Name column. I'm thinking equal "weight" in the flex layout as we give to the Message, because the Message is only used for details. Otherwise, they use the Name as the main description of the history update.

Fixed width of `name` column, also made small changes in render headers in `ItemsTable` component.
<img width="1792" alt="Screenshot 2022-12-13 at 21 23 42" src="https://user-images.githubusercontent.com/33761040/207426105-46cf60e6-0727-4779-958e-6ea131bbf007.png">

2022-12-13 20:15 UTC, stefcameron approved these changes
Thanks for adjusting the column widths. Looks great, nice work!

2022-12-13 20:56 UTC, merged