PRODX-19642-PR1: AuthAccess to Cloud
Mirantis/lens-extension-cc pull request #622
Opened 2021-12-01 10:59 UTC by AntonNos

Renamed AuthAccess to Cloud, added new property cloudUrl and dropped usesSso property

2021-12-01 18:03 UTC, stefcameron commented
👀

2021-12-01 18:38 UTC, stefcameron requested changes
The auto-login when the extension is loaded is actually happening because of code in useClusterLoader.js, not the effect in Login.js. If you've already connected once before, then we have the URL, and on load, we attempt to get the config, which succeeds, and then we see that we have an invalid Cloud object, so we assume we should connect to get tokens: https://github.com/Mirantis/lens-extension-cc/blob/master/src/renderer/hooks/useClusterLoader.js#L127

But I think that's OK. We're going to make many other changes to the whole connection process that will quickly make this problem irrelevant anyway. So it's fine for now.

2021-12-01 18:38 UTC, stefcameron commented on src/renderer/auth/Cloud.js
> +    //
Missing a comment here, like "URL to the MCC instance"

2021-12-01 18:38 UTC, stefcameron commented on src/renderer/auth/Cloud.js
>   * Captures API authorization tokens and expiries.
I think we should update this JSDoc comment to more clearly identify what this class now represents, something like,

```
Represents a connection to a single MCC instance (i.e. Management Cluster),
including access tokens and expiry times.
```

2021-12-01 18:38 UTC, stefcameron commented on lens-extension-cc
> +/Users/anos/.k8slens/extensions/lens-extension-cc
This shouldn't be included in the PR. Looks like a file to be deleted.

2021-12-01 18:38 UTC, stefcameron commented on src/renderer/components/GlobalPage/Login.js
> +        // }
Let's delete this old commented code.

2021-12-01 18:40 UTC, AntonNos commented on src/renderer/components/GlobalPage/Login.js
> +        // }
I commented it because I thought that we still need Notifications.error, but not sure where should I place it.

2021-12-01 19:11 UTC, stefcameron commented on src/renderer/components/GlobalPage/Login.js
> +        // }
It'll change completely, so we can drop it for now. I'll ask Michal to add this error case to the mocks.

2021-12-02 11:15 UTC, AntonNos commented on src/renderer/auth/Cloud.js
> +    //
Comment added

2021-12-02 11:15 UTC, AntonNos commented on src/renderer/auth/Cloud.js
>   * Captures API authorization tokens and expiries.
Updated

2021-12-02 11:16 UTC, AntonNos commented on lens-extension-cc
> +/Users/anos/.k8slens/extensions/lens-extension-cc
File was deleted

2021-12-02 11:16 UTC, AntonNos commented on src/renderer/components/GlobalPage/Login.js
> +        // }
Deleted

2021-12-02 19:56 UTC, stefcameron reviewed
Thanks for fixes. Just 2 more small things.

2021-12-02 19:56 UTC, stefcameron commented on src/renderer/auth/Cloud.js
> +    cloudUrl: [rtv.OPTIONAL, rtv.STRING],
One last thing I just noticed: This should be
```suggestion
    cloudUrl: [rtv.EXPECTED, rtv.STRING],
```
because the property is no longer optional. We want all Cloud instances to have a `cloudUrl`. But then you need to be able to `new Cloud()` to create one where `cloudUrl` will be null, initially, so in terms of [RTV.js](https://rtvjs.stefcameron.com/) validations, that means the value is `EXPECTED`. (RTV.js is a runtime validation library I wrote.)

2021-12-02 19:56 UTC, stefcameron commented on src/renderer/auth/Cloud.js
>          const normalizedNewValue = newValue ?? null; // undefined -> null
And then this should change to
```suggestion
        const normalizedNewValue = newValue || null; // '' or undefined -> null
```
so that we also normalize empty strings to null since an empty string means nothing here. It's either null or a non-empty string. Before, it was `usesSso` and it was a boolean, which had different normalization requirements because a boolean is either true or false (and if not set, we'd normalize to null).

2021-12-06 10:12 UTC, AntonNos commented on src/renderer/auth/Cloud.js
> +    cloudUrl: [rtv.OPTIONAL, rtv.STRING],
fixed

2021-12-06 10:12 UTC, AntonNos commented on src/renderer/auth/Cloud.js
>          const normalizedNewValue = newValue ?? null; // undefined -> null
fixed

2021-12-06 14:07 UTC, stefcameron approved these changes
Thanks for the fixes, good to merge!

Note that when you merge this, you'll need to rebase your local "PR2" branch onto master and then force-push the result to your "PR2" branch in order to get it updated to just the "PR2" changes. Otherwise, GitHub will continue to show "PR2" as being all the changes from "PR1" and "PR2". LMK if you have any questions about that.

2021-12-07 12:19 UTC, merged