PRODX-19642-PR2: added ssoUtil
Mirantis/lens-extension-cc pull request #623
Opened 2021-12-01 11:02 UTC by AntonNos

Moved _startAuthorization and _finishAuthorization methods from SsoAuthProvider to new ssoUtil

2021-12-01 19:08 UTC, stefcameron requested changes
I added lots of comments here to try to be helpful. Hopefully it helps.

2021-12-01 19:08 UTC, stefcameron commented on src/util/ssoUtil.js
> +      pr.error = strings.ssoAuthProvider.error.authCode();
Same thing here about state which no longer applies. So just fail the promise:

```suggestion
    throw new Error('Failed to get username from token JWT');
```

2021-12-01 19:08 UTC, stefcameron commented on src/util/ssoUtil.js
> +  pr.onChange();
Does not apply because it's state.

2021-12-01 19:08 UTC, stefcameron commented on src/util/ssoUtil.js
> +};
Please configure your IDE to add an empty line on save. In VSCode, that's `"editor.renderFinalNewline": true,` in your preferences for this workspace.

2021-12-01 19:08 UTC, stefcameron commented on src/renderer/store/SsoAuthProvider.js
> -  }
So now here, everything here that is _not_ setting state goes away because the utility method is handling it. But state still needs to be handled here, otherwise everything breaks.

```suggestion
  try {
    ssoUtil.finishAuthorization({ oAuth, config, cloud });
  } catch {
    pr.error = strings.ssoAuthProvider.error.authCode();
  }
```

2021-12-01 19:08 UTC, stefcameron commented on src/renderer/store/SsoAuthProvider.js
> -  pr.onChange();
Keep this too.

2021-12-07 18:33 UTC, AntonNos commented on src/renderer/store/SsoAuthProvider.js
> -  }
We can get the error fro catch like that:
`try {
            finishAuthorization(options);
          } catch (error) {
            pr.error = error;
          }`

2021-12-07 18:34 UTC, AntonNos commented on src/util/ssoUtil.js
> +  pr.reset(true);
Done

2021-12-07 18:34 UTC, AntonNos commented on src/util/ssoUtil.js
> +export const _startAuthorization = async function ({ config }) {
Done

2021-12-07 18:34 UTC, AntonNos commented on src/util/ssoUtil.js
> +export const _finishAuthorization = async function ({ oAuth, config, cloud }) {
Done

2021-12-07 18:34 UTC, AntonNos commented on src/util/ssoUtil.js
> + * NOTE: This method ASSUMES `loading` is `true` (i.e. load is in progress).
Done

2021-12-07 18:34 UTC, AntonNos commented on src/util/ssoUtil.js
> + *  to Lens and ultimately call back into `_finishAuthorization()`.
Done

2021-12-07 18:34 UTC, AntonNos commented on src/util/ssoUtil.js
> +      pr.error = strings.ssoAuthProvider.error.authCode();
Done

2021-12-07 18:35 UTC, AntonNos commented on src/util/ssoUtil.js
> +  pr.onChange();
Done

2021-12-07 18:35 UTC, AntonNos commented on src/util/ssoUtil.js
> +};
Done

2021-12-07 18:35 UTC, AntonNos commented on src/renderer/store/SsoAuthProvider.js
> -  pr.onChange();
Done

2021-12-07 18:53 UTC, stefcameron commented on src/renderer/store/SsoAuthProvider.js
> -  }
Yes, but the point is that we're generating a __user-facing__ error message, not just giving them the "cyptic" generated error message. So we want to use our own (more generic, but still specific enough) error string instead of the "raw" error message.

Also note that the error object here is an __object__, not a string, and `pr.error` is a string. But regardless, we want to use our own user-facing string.

2021-12-08 23:48 UTC, stefcameron commented
Hmm, I tried these latest changes locally, and this is what I get after authenticating in the browser:
![image](https://user-images.githubusercontent.com/2855350/145309217-0e966f0f-63ac-4efe-a36f-67dae30ad0f2.png)

2021-12-09 00:00 UTC, stefcameron commented
Something's still not right with commits on this PR because I'm still seeing all of PR1 changes on it:

![image](https://user-images.githubusercontent.com/2855350/145309506-88ea1a60-a40c-4a93-b2be-b444f33c007c.png)

Also, I don't see the fix I committed yesterday for the `cloudUrl`.

What should've happened on your local system is this, in git commands:
```bash
# starting by assuming the current branch is PRODX-19642-PR2
$ git log -3 --pretty=oneline # get latest 3 commits (since I think you made 3 commits after the first review)
644d1dadb35d03054040c58ab560ba1a6a72420e (HEAD -> PRODX-19642-PR2, origin/PRODX-19642-PR2) comments fixes
c163243cf55c2c070a6023d33f8b565c61c1a759 fixed comments
2787c983ddb834f598993742521d76e08508ff5c changed path in ssoUtil
$ git checkout master
$ git pull --rebase # update to latest origin/master -- I'm assuming you cloned the repo, so you don't have a fork
$ git checkout -b NEW-PR2 origin/master # new PR2 branch directly off origin/master
$ git cherry-pick 2787c983ddb834f598993742521d76e08508ff5c # oldest of the 3 "changed path in ssoUtil"
$ git cherry-pick c163243cf55c2c070a6023d33f8b565c61c1a759 # 2nd one "fixed comments"
$ git cherry-pick 644d1dadb35d03054040c58ab560ba1a6a72420e # 1st one "comments fixes"
$ git push -f origin HEAD:PRODX-19642-PR2 # force-update original PR2 branch on GitHub
```
At this point, PRODX-19642-PR2 on GitHub should have only the changes related to the work in PR2, nothing of PR1.

Now in git, there's like 10 different ways of achieving the same thing, so it's possible you know other commands, but this is the gist of it. The end-result should be the same.

Another solution, at this point, since your newer PR PRODX-19642-ssoUtil looks like it has just the changes we should have here, is to do this:
```bash
$ git checkout PRODX-19642-ssoUtil
$ git push -f origin HEAD:PRODX-19642-PR2
```
And keeps working from PRODX-19642-ssoUtil locally, but pushing to PRODX-19642-PR2 on origin (GitHub).

Of course, once you've done the force-push, you don't need to keep doing that again for subsequent commits (unless you need to rebase from master again to get some changes there for some reason).

2021-12-10 15:09 UTC, stefcameron commented
Dropping in favor of #630

2021-12-10 15:09 UTC, closed without merging