[PRODX-19642]: added ssoUtil
Mirantis/lens-extension-cc pull request #630
Opened 2021-12-08 15:01 UTC by AntonNos

2021-12-09 00:11 UTC, stefcameron requested changes

2021-12-09 00:11 UTC, stefcameron commented on src/util/ssoUtil.js
> +    throw new Error(strings.ssoAuthProvider.error.authCode());
Should just throw the original error here (I admit it would be less confusing to rename the local `error` variable to `errorMsg` so it's more obvious it's a string, not an Error object):
```suggestion
throw new Error(error);
```

2021-12-09 00:11 UTC, stefcameron commented on src/renderer/store/SsoAuthProvider.js
> +            pr.error = error;
As I mentioned on the original PR, `error` is an object here, while `pr.error` is a string, and it's user-facing, so this should be:
```suggestion
pr.error = strings.ssoAuthProvider.error.basicOnly();
```

2021-12-09 00:11 UTC, stefcameron commented on src/util/ssoUtil.js
> +    throw new Error(strings.ssoAuthProvider.error.basicOnly());
Since this is a utility module, we don't need to use a user-facing string for this:
```suggestion
throw new Error('Cloud instance does not support SSO');
```

2021-12-09 00:11 UTC, stefcameron commented on src/util/ssoUtil.js
> +};
Instead of this, let's just export each function directly. This is more like the CJS style where we'd do:
```javascript
module.exports = {
  startAuthorization,
  finishAuthorization,
}
```

2021-12-09 00:11 UTC, stefcameron commented on src/util/ssoUtil.js
> +const finishAuthorization = async function ({ oAuth, config, cloud }) {
```suggestion
export const finishAuthorization = ...
```

2021-12-09 00:11 UTC, stefcameron commented on src/util/ssoUtil.js
> +const startAuthorization = function ({ config }) {
```suggestion
export const startAuthorization = ...
```

2021-12-09 00:11 UTC, stefcameron commented on src/renderer/auth/Cloud.js
> +    cloudUrl: [rtv.OPTIONAL, rtv.STRING],
Should back this out. It should be EXPECTED...

2021-12-09 00:11 UTC, stefcameron commented on src/renderer/auth/Cloud.js
> +        const normalizedNewValue = newValue && null; // '' or undefined -> null
Should back this out. The `||` is the right way to do it because an empty string will become `null`, which is what we want. The property is either a non-empty string, or it's null. An empty string is not a possibility. Hence, we "normalize" any falsy values to null.

2021-12-09 12:38 UTC, AntonNos commented on src/util/ssoUtil.js
> +};
Exported this modules without `module.exports`, because received this error:
[EXTENSIONS-LOADER]: can't load renderer for "@mirantis/lens-extension-cc": Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./src/util/ssoUtil.js

2021-12-09 15:55 UTC, stefcameron commented on src/util/ssoUtil.js
> +};
Oops, looks like I didn't finish my though on my original comment for some reason. 🤷‍♂️ I must've seen a squirrel outside or something...

What I meant to say was that what you're doing here _is like_ the CJS `module.exports = {...}` style, but with ESM, we can export things directly, so _instead_ of this, just use
```javascript
export const startAuthorization = function (...) {...};

export const finishAuthorization = function (...) {...};
```

2021-12-09 15:58 UTC, stefcameron commented on src/util/ssoUtil.js
> +};
That will allow importing in different ways:
```javascript
import { startAuthorization } from './ssoUtil';

startAuthorization(...);

---

import * as ssoUtil from './ssoUtil';

ssoUtil.startAuthorization(...);
```

If you do it the way you're doing it, then the second import above wouldn't work well. You'd end-up with `ssoUtil.ssoUtil.startAuthorization()`, and the first import would fail because we're only exporting one symbol, which is an object named `ssoUtil`.

2021-12-09 17:17 UTC, stefcameron commented on src/util/ssoUtil.js
> +};
Looks like you understood what I was saying after all. 😄

2021-12-09 17:27 UTC, stefcameron requested changes
The code looks OK, but we still have the problem that after these changes, the extension no longer works -- and these changes should not cause anything to break. I don't get any clusters back anymore. This is what I see after doing the SSO sign in:

![image](https://user-images.githubusercontent.com/2855350/145445888-805589c9-8381-4072-9ef0-b1a22ba63937.png)

2021-12-09 17:27 UTC, stefcameron commented
I should be seeing the list of available clusters...

2021-12-09 18:06 UTC, stefcameron commented
This is what we should see after SSO:

![image](https://user-images.githubusercontent.com/2855350/145451520-ba1d2cf9-456e-4c35-a673-eabdf281c963.png)

2021-12-10 14:53 UTC, stefcameron commented on src/renderer/store/SsoAuthProvider.js
> +            ssoUtil.finishAuthorization(options);
I think this is the problem why it's not working: We're not `await`-ing this async function...

2021-12-10 14:54 UTC, stefcameron commented on src/renderer/store/SsoAuthProvider.js
> +            ssoUtil.finishAuthorization(options);
Hmm, but we weren't awaiting it before... OK, maybe that's not it.

2021-12-13 21:07 UTC, stefcameron approved these changes
This looks good! Thanks for fixing that elusive bug!

2021-12-13 22:03 UTC, merged