PRODX-20593 Add new MCC Connection page
Mirantis/lens-extension-cc pull request #659
Opened 2022-01-04 15:24 UTC by bnalisnikovskiy

To go to new page do `shift+click` on SyncPage title. 
this is just a mockup. All other logic and connection with other parts will be added in the future tickets

![image](https://user-images.githubusercontent.com/95434160/148081604-aab0ea4d-8b4f-4754-861c-ba7876f93d3f.png)

2022-01-04 22:43 UTC, stefcameron requested changes
Could of strings that should be in `strings.ts` and some thoughts on establishing the SSO connections...

2022-01-04 22:43 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +      <Title>Select projects to synchronize</Title>
This string should be in `strings.ts`

2022-01-05 08:50 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/GlobalPage.tsx
> +import { lightThemeClassName, lightTheme, darkTheme } from '../theme.js';
No, it's me. My IDE (WebStrom from JetBrans) cannot recognize those imports. I mean, if file is `.tsx` then import without extension doesn't work (in IDE). Probably it tries fo find `ts` file as well. I didn't find a way to fix that and allow 'mixing' file types fro IDE

2022-01-05 08:52 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/AddCloudInstance.js
> +export default AddCloudInstance;
It's my fast template adds that. If we don't use default imports, lets keep general strategy and use one approach.

2022-01-05 08:53 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +      <Title>Select projects to synchronize</Title>
This is temporary file. In should be filled in https://mirantis.jira.com/browse/PRODX-20596. It just a 'booked place' for component

2022-01-05 10:05 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/ConnectionBlock.js
> +    configActions.load(normUrl); // implicit reset of current config, if any
Thanks for detailed explanation. It should work as you described and this logic will be added later in the separate PR when all needed parts will be ready. For now it's temporary function, 'just for now' and it will be totally changed/replaced 

This PR mostly only about UI, and main goal for now is unblock creation SynchronizeBlock ([PRODX-20596](https://mirantis.jira.com/browse/PRODX-20596). Many UI work should be done there as well

2022-01-05 10:12 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/AddCloudInstance.js
> +const AddCloudInstance = ({ setShowNewDesign }) => {
Got it. And it should be done as you described. As I mentioned in PR description, for now, a goal is create a UI component, all 'real' logic will be added later when CloudStore will be ready and other needed work will be done.  Currently, this `setShowNewDesign` it's a temporary func to just a show new page.  I don't want to add `onAdd`, `onCancel` on current stage, since we don't have real parts for that

2022-01-05 16:18 UTC, stefcameron commented on src/renderer/components/GlobalPage/GlobalPage.tsx
> +import { lightThemeClassName, lightTheme, darkTheme } from '../theme.js';
It's strange that it only updated that specific import, and not all the other ones too, since by this logic, wouldn't they all exhibit the same issue in WebStorm?

2022-01-05 16:32 UTC, stefcameron commented on src/renderer/components/GlobalPage/ConnectionBlock.js
> +    configActions.load(normUrl); // implicit reset of current config, if any
OK. Seems obvious it needs to change later.

2022-01-05 16:35 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/GlobalPage.tsx
> +import { lightThemeClassName, lightTheme, darkTheme } from '../theme.js';
I meat that I did that in purpose. Because without file extension variables seem as unused inside their files. IDE just can't 'net' them. Later I'll try to find solution again...  
![image](https://user-images.githubusercontent.com/95434160/148253886-f42b3a65-353b-4b1d-b321-072444d72aea.png)

2022-01-05 16:44 UTC, bnalisnikovskiy commented
Sure. It's not a big deal. Fixed

2022-01-05 16:59 UTC, stefcameron commented
> Sure. It's not a big changes. Now I see what you meant. Fixed

Thank you! 😄

2022-01-05 17:01 UTC, stefcameron commented on src/renderer/components/GlobalPage/GlobalPage.tsx
> +import { lightThemeClassName, lightTheme, darkTheme } from '../theme.js';
Strange. Doesn't WebStorm use ESLint (and our specific configuration of it) for linting the code? Seems like it's using its own linter with its own rules. Maybe that's a clue to fixing this.

2022-01-05 17:02 UTC, stefcameron approved these changes
Looks good!

2022-01-05 17:03 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/GlobalPage.tsx
> +import { lightThemeClassName, lightTheme, darkTheme } from '../theme.js';
It uses Eslint as well, and have its own internal checks

2022-01-05 17:15 UTC, merged