[PRODX-20592]: Added new Welcome page (UI Part)
Mirantis/lens-extension-cc pull request #663
Opened 2022-01-05 15:23 UTC by AntonNos

![Screenshot 2022-01-05 at 17 18 41](https://user-images.githubusercontent.com/33761040/148242611-d6b5af94-e5bb-41af-b08b-2c7eafb701fc.png)
Logic will be added in separate PRs

2022-01-05 15:45 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/WelcomeView.js
> +    marginBottom: 36,
I think better use `layout.gap, .pad, .grid` as a base for margin and paddings.

Just nitpick

2022-01-05 20:00 UTC, stefcameron requested changes

2022-01-05 20:00 UTC, stefcameron commented on src/renderer/components/GlobalPage/WelcomeView.js
> +    marginBottom: 36,
It would be better, yes. Doing it that way would help us stick to a common pixel grid, which could help with alignment. Like I noticed the `maxWidth` of the `WelcomeInner` component is 717px -- why 717px? Seems odd (pardon the pun! 😉)

Not a blocker, but so far, I've tried to do as Bogdan has indicated.

2022-01-05 20:00 UTC, stefcameron commented on src/renderer/components/GlobalPage/WelcomeView.js
> +    color: 'var(--blue)',
Looks like Lens is using `--primary` for links. It's the same HEX value, but let's use the same variable as Lens is using.

2022-01-05 20:00 UTC, stefcameron commented on src/renderer/components/GlobalPage/WelcomeView.js
> +            <ContainerCloudIcon size={100} fill="#FFFFFF" />
This fill should use a CSS Var so that it updates to a dark shade if the theme changes to Light mode. Looks like that would be `--textColorAccent`, which is white in Dark mode, and near black in Light mode.

2022-01-05 20:00 UTC, stefcameron commented on src/strings.ts
> +  `,
When the string is HTML (that would require `dangerouslySetInnerHTML` to use it), I add "Html" to the end of the string name, like `titleHtml` and `listItemsHtml` in this case. See `login.sso.messageHtml` as an example.

2022-01-05 20:00 UTC, stefcameron commented on src/strings.ts
> +      'https://github.com/Mirantis/lens-extension-cc/blob/master/README.md',
A URL is more of a constant than a string. Could we put this in `constants.js`?

2022-01-05 20:00 UTC, stefcameron commented on yarn.lock
> +
Unfortunately, we can't use MDS components in Lens. MDS packages are private, and this extension is public. Also, the style will be very different from what Lens components look like. We have to use Lens components only.

2022-01-06 12:40 UTC, AntonNos commented on src/renderer/components/GlobalPage/WelcomeView.js
> +    marginBottom: 36,
Fixed

2022-01-06 12:41 UTC, AntonNos commented on src/renderer/components/GlobalPage/WelcomeView.js
> +    color: 'var(--blue)',
Fixed

2022-01-06 12:41 UTC, AntonNos commented on src/strings.ts
> +  `,
Fixed

2022-01-06 12:41 UTC, AntonNos commented on src/strings.ts
> +      'https://github.com/Mirantis/lens-extension-cc/blob/master/README.md',
Fixed

2022-01-06 12:41 UTC, AntonNos commented on yarn.lock
> +
Fixed

2022-01-06 17:55 UTC, stefcameron approved these changes
Thanks for making those changes!

2022-01-06 20:25 UTC, merged