[PRODX-20596]: added synchronized block
Mirantis/lens-extension-cc pull request #671
Opened 2022-01-13 12:50 UTC by AntonNos

![Screenshot 2022-01-13 at 14 47 34](https://user-images.githubusercontent.com/33761040/149333431-15e228a2-a16c-491e-b10e-d5f5920e74a1.png)

2022-01-13 14:30 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +              <li key={index}>
I guess `project.projectName` is better for `key`

2022-01-13 23:59 UTC, stefcameron requested changes
Nice work on the layout; looks great, visually! 😄

2022-01-13 23:59 UTC, stefcameron commented on src/renderer/components/Accordion/ChevronIcon.js
> +  );
Icons should come from Material (where Lens gets all its icons). So this would be one of their "chevron" icons, like https://fonts.google.com/icons?selected=Material%20Icons%3Achevron_right%3A

2022-01-13 23:59 UTC, stefcameron commented on src/renderer/components/Checkbox/CheckIcon.js
> +  );
https://fonts.google.com/icons?selected=Material%20Icons%3Acheck%3A

2022-01-13 23:59 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +import { useState, useEffect } from 'react';
Nice job on a Checkbox component, but why do we have our own Checkbox? Lens already provides us with a Checkbox component. For example, we use one in the existing code in the `ClusterList` component: https://github.com/Mirantis/lens-extension-cc/blob/4a9beeee39c8a93213d1227190521e146e5d4326/src/renderer/components/GlobalPage/ClusterList.js#L137

Before making any components of our own, we need to check what Lens offers and use those first. The Onboarding wiki I wrote provides information about where to find what components Lens provides.

2022-01-13 23:59 UTC, stefcameron commented on src/renderer/components/GlobalPage/CaretIcon.js
> +};
This is probably https://fonts.google.com/icons?selected=Material%20Icons%3Aarrow_drop_up%3A

2022-01-13 23:59 UTC, stefcameron commented on src/renderer/components/Accordion/Accordion.js
> +export const Accordion = ({ title, children }) => {
Please make sure Lens doesn't already have this kind of component. I don't think so, but we better have a look to be sure.

2022-01-13 23:59 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +            label="Project name"
Please move this string into the `strings.ts` module.

2022-01-13 23:59 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  const [projectsList, setProjectsList] = useState(mockedProjects);
Ultimately, the list of projects and their data should be coming from a prop that will be passed into this component. Is that work for later, or something you forgot to do?

2022-01-14 11:07 UTC, AntonNos commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  const [projectsList, setProjectsList] = useState(mockedProjects);
I mocked data only for now to test component and check UI part. Of course I will delete mocked data once all functionality will be done:)

2022-01-14 11:09 UTC, AntonNos commented
> Nice work on the layout; looks great, visually! 😄

Thank you! Going to fix all your comments

2022-01-14 11:26 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  const [projectsList, setProjectsList] = useState(mockedProjects);
You can pass it as a prop and set `mockedProjects` as default prop in `defaultPropTypes` 
But I think this structure will be changed. 
As I can see we will pass something like this 
`selectedCloud: {
cloud: Cloud
namespaces: [...],
clusters: [...],
sshKeys: [...],
...
}`

And action `cloudStore.clouds[selectedCloud.cloud.cloudUrl] = selectedCloud.cloud` will happen here after 'sync' button click (not at `ConnectionBlock`, as we do now). In ConnectionBlock we create `new Cloud()`, fetch all needed data, construct `selectedCloud` and set it to parent (`AddCloudInstance`) local state.
Then it should looks like `<SynchronizeBlock cloud={selectedCloud} />` and all work to store on disk and sync should be called from `SynchronizeBlock` 

Does it make sense @stefcameron ?

2022-01-14 15:53 UTC, AntonNos commented on src/renderer/components/Checkbox/Checkbox.js
> +import { useState, useEffect } from 'react';
Yes, I saw that checkbox in `ClusterList`, but looks like we need to have custom icon (minus) in checkbox if `isAllCkecked` is false. Plus need to add handler to `Checkbox` component to handle state in parent component  (which I can't do with Lens Checkbox component). That why I created our own `Checkbox`

2022-01-14 16:00 UTC, AntonNos commented on src/renderer/components/Accordion/Accordion.js
> +export const Accordion = ({ title, children }) => {
Okay, thank you! I will check them in the future work. Looks like we don't have `Accordion` (or similar) component in Lens

2022-01-14 16:02 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  const [projectsList, setProjectsList] = useState(mockedProjects);
I think we ended-up chatting about this in Slack. We should have an `ExtendedCloud` class that is created with a `Cloud` object.

ExtendedCloud can own the sync timer, have properties like `clusterCount`, `credentialCount`, etc., and fire "update" events (similar to how Cloud fires "status update" events) whenever that data is updated. ExtendedCloud can contain all the API access logic to get all the metadata we want to display for a given Cloud so that we keep all that out of the Cloud class itself since it's already pretty complex.

Then we can simply give an ExtendedCloud object to something like the SyncBlock and it can just use its properties and subscribe to its event in order to display what it needs to. `extendedCloud.cloud.syncNamespaces` and `extendedCloud.cloud.syncAll`, for example, will tell us which projects are synced. `extendedCloud.clusterCount` will tell us the number of clusters. Etc. `<SyncBlock extCloud={new ExtendedCloud(cloud)} />`

Later, when we get to the SyncManager (step 12 in the Google Doc), we can use ExtendedCloud to get more than just counts, but all the objects.

So perhaps we'll want to end-up with a context provider (similar to ClusterDataProvider that exists today and will go away) that provides ExtendedCloud objects to the entire "app" (i.e. extension). That provider observes CloudStore.clouds for changes, and updates its list of extended cloud objects by doing something like `cloudStore.clouds.map((c) => new ExtendedCloud(c))`.

2022-01-14 16:07 UTC, stefcameron commented on src/renderer/components/Accordion/Accordion.js
> +export const Accordion = ({ title, children }) => {
Thanks for checking!

2022-01-14 16:29 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +          aria-checked="false"
This attribute should be one of "true", "mixed", or "false" depending on the Checkbox's state.

2022-01-14 16:29 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +import { useState, useEffect } from 'react';
Ah, yes, we need a tri-state checkbox and Lens' checkbox is only dual-state. But I don't see any indication of a third state in the code. It's all binary, as far as I can tell. Is that something you're planning on adding later?

2022-01-14 16:29 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +    handleChildCheckbox && handleChildCheckbox(isChecked);
Ideally, a Checkbox shouldn't know about any other Checkbox. The fact that all checkboxes (projects) are checked, including the parent, or that some checkboxes are checked and the parent is partially checked, should only be the concern of the SynchronizeBlock component. The SynchronizeBlock has access to all checkboxes, and so should own/set/manage the state of each one.

2022-01-14 16:29 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +          aria-checked="false"
But we aren't concerned about accessibility in Lens. So it might be better just to remove all the `aria-` attributes.

2022-01-14 16:32 UTC, AntonNos commented on src/renderer/components/Checkbox/Checkbox.js
> +import { useState, useEffect } from 'react';
Yes, I just see that 3rd state when answered your comment. I'm working on it right now and will and it in next commit (together with all "after review" fixes)

2022-01-16 23:57 UTC, AntonNos commented on src/renderer/components/Checkbox/Checkbox.js
> +import { useState, useEffect } from 'react';
Added 3rd state

2022-01-18 20:53 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +                color: 'rgb(23, 34, 47)',
Will this (and line 78) hard coded color work when the them is changed from dark to light or vice versa?

2022-01-18 20:53 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +  isCheckedFromParent: PropTypes.bool,
What does this prop mean? Can we just call it "checked"? Having this "parent" reference in the name seems to make this more complicated than it is: A tri-state checkbox.

2022-01-18 20:53 UTC, stefcameron commented on src/renderer/components/Checkbox/Checkbox.js
> +  isMinusIcon: PropTypes.bool,
So if `isMinusIcon` is true, then it's indeterminate regardless of `isCheckedFromParent`? `isMinusIcon` seems too implementation-specific -- like what if we changed it to be a filled square instead of a hyphen when the component is in an indeterminate state...?

How about we merge `isMinusIcon` and `isCheckedFromParent` into one prop, `value`, and provide an export that is an enumeration of supported values "CHECKED", "UNCHECKED", "MIXED"?

```javascript
export const values = {
  CHECKED: "CHECKED",
  UNCHECKED: "UNCHECKED",
  MIXED: "MIXED"
};
```

Now we could have `<Checkbox value={values.MIXED} />` to set it into its indeterminate state, regardless of what that looks like visually. And in the code, there's no confusion as to how the Checkbox should render: Checkmark, empty, or hyphen.

And finally, since Lens already has a `<Checkbox>` component, we should really name this one something different so there's no confusion. Maybe "TriStateCheckbox" or something?

2022-01-18 21:43 UTC, AntonNos commented on src/renderer/components/Checkbox/Checkbox.js
> +                color: 'rgb(23, 34, 47)',
Fixed

2022-01-18 21:44 UTC, AntonNos commented on src/renderer/components/Checkbox/Checkbox.js
> +  isCheckedFromParent: PropTypes.bool,
Fixed

2022-01-19 11:20 UTC, bnalisnikovskiy requested changes

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  };
Move away from component. And 'values' isn't very proper name. eg `PARENT_VALUES = Object.freeze({...})`

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +        ...currentCheckboxState,
this is not necessary. You are rewrite all values anyway

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +        ...currentCheckboxState,
this is not necessary. You are rewrite all values anyway

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +        (el, i) => (index === i ? (el = !el) : el)
It may be simpler ` (el, i) => (index === i ? !el : el)`

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +          (el) => (el = !currentCheckboxState.parent)
It may be simpler `() => !currentCheckboxState.parent`

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +    } else {
`else` is not necessary. Just return

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +            {projectsList.map((namespace, index) => (
it would be easier if instead of indexes we will use namespace names. In the result we need to know their names anyway.
So instead of `[true, false]` array we would have `{ name1: true, name-two: false }`.
It also may be more safe since we have sorting (change order) here

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +              style={{
Lets move styles Objects from Component (here and on line 63)
Just call them `removeIconStyle`, `checkIconStyle` etc, and keep outside of component

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +            onChange={() => onChange()}
You can use just `onChange`. Arrow func isn't needed here, as I can see

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +};
If propTypes aren't required you have to set defaultProps. 
So `.isRequired` or defaultProp

2022-01-19 11:20 UTC, bnalisnikovskiy commented on src/renderer/components/Accordion/Accordion.js
> +            style={{
Better to keep style objects outside of component to avoid extra creations

2022-01-19 16:00 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  };
I meant for this enumeration to be defined by, and exported from, TriStateCheckbox, since that's the component that uses these values. The enumeration should be _imported_ here, and then used throughout the code like `checkValues.CHECKED` to check one of the TriStateCheckbox components.

The values are not specific to the parent. If `values` alone is too generic, then maybe `checkValues`?

2022-01-19 17:54 UTC, stefcameron reviewed
TriStateCheckbox is looking good...!

2022-01-19 17:54 UTC, stefcameron commented on src/renderer/components/GlobalPage/AddCloudInstance.js
> +// import { mockedProjects } from './mockedProjects';
This comment should be removed.

2022-01-19 17:54 UTC, stefcameron commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +        <CheckboxControl isChecked={value !== 'UNCHECKED'}>
"UNCHECKED" should come from the enumeration, like `checkValues.UNCHECKED`, instead of being hard coded.

2022-01-19 17:54 UTC, stefcameron commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +          {value === 'MIXED' && (
Same for "MIXED"

2022-01-19 17:54 UTC, stefcameron commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +          {value === 'CHECKED' && (
Same for "CHECKED"

2022-01-19 17:54 UTC, stefcameron commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +            checked={value !== 'UNCHECKED'}
Same for "UNCHECKED"

2022-01-19 17:54 UTC, stefcameron commented on src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
> +  isMinusIcon: PropTypes.bool,
Now that we have `value` prop, we don't need `isChecked` and `isMinusIcon`.

2022-01-20 14:40 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
You should check  if `extCloud` is present and return null if it's not

2022-01-20 14:42 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  if (!projectsList) {
See my comment above. Instead of this part you can add 
`if(extCloud?.namespaces) {
return null
}`

2022-01-20 14:53 UTC, AntonNos commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
We will have linter error if we add `if` statement before `useState`

2022-01-20 14:53 UTC, AntonNos commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +  if (!projectsList) {
We will have linter error if we add `if` statement before `useState`

2022-01-20 16:21 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
That's true. React "rules of hooks" means we can't conditionally execute a hook. You'll also have to deal with the fact that the ExtendedCloud object may not yet be loaded when you get it. You'll need to check its `loading` property and subscribe to its LOADING_CHANGE event. But not just on first load of SynchronizeBlock. This should be done such that at any time, even after the SynchronizeBlock has been rendered, the ExtendedCloud object might go into loading state (because it'll be refreshing its data every 5 minutes).

@bnalisnikovskiy This reminds me, ExtendedCloud should have another event like DATA_UPDATED to signal when its data (i.e. `namespaces` property) has been updated.

The point is that the `loading` property (and LOADING_CHANGE event) represent the initial data load where any UI rendering the ExtendedCloud __must__ show a spinner because there's no data. But once we have data, 5 minutes later, we'd going to refresh it -- but we'll still have data to show while we're refreshing (the known/existing data). So UI that's rendering the ExtendedCloud instance will want to continue showing the current data right up until there's new data available. Otherwise, every 5 minutes, the whole UI would go into "spinner mode", which won't be nice. So components rendering an ExtendedCloud object will need to be notified when new data is available (i.e. ExtendedCloud.namespaces has been updated). To do that, they can listen for the DATA_UPDATED event.

And probably if there's an error during refresh, we should log the error and just not do anything (i.e. don't fire the event, and don't touch the existing `ExtendedCloud#namespaces` property so that components rendering it will continue to render the last-known data. Or we could set an `error` property with a message and set `namespaces = undefined`, but that would further complicate any component that renders an ExtendedCloud object.

@AntonNos The point I'm making is that if `extCloud.loading === true`, SynchronizeBlock will need to show a spinner (because `extCloud.namespaces` will be undefined) and listen for the LOADING_CHANGE event. Once the data is loaded, it'll also need to listen for DATA_UPDATED and then update according to the new `extCloud.namespaces` object.

2022-01-20 16:23 UTC, stefcameron commented on src/strings.ts
> +    sshKeys: () => 'ssh keys',
Let's make "ssh" -> "SSH" (all caps) since it's an acronym.

2022-01-20 16:23 UTC, stefcameron reviewed
TriStateCheckbox is looking solid now, thank you!

2022-01-20 16:27 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
I think it's a bit overcomplicated. I thought do add check on AddCloudInstance level, and don't show SynchronizeBlock until ExtCloud will be loaded.

2022-01-20 16:37 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
We'll still need this mechanism in ExtendedCloud for the SyncView. If we're really only going to use the SynchronizeBlock for the sole purpose of the AddCloudInstance wizard, then OK, I agree it only needs to deal with the `loading` property. But it seems to me we'll want to use it in the SyncView in "read-only" mode (without the checkboxes) since we need to show the exact same UI there (just without the checkboxes) with collapsing section to show details under projects, etc. So then we'll need it to handle what I just described...

2022-01-20 16:43 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
You're right. Noted about DATA_UPDATED. I'll add that (if not find better solution) on next step, together with `ExtendedCloudProvider`

2022-01-20 18:07 UTC, bnalisnikovskiy approved these changes

2022-01-21 15:26 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
Will the handling of the LOADING_CHANGE event be added in a subsequent PR?

2022-01-21 15:28 UTC, stefcameron requested changes

2022-01-21 15:28 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +    },
I would feel more comfortable committing this to master (and so "forever" in the history of this public repo) if the data was at least anonymized. Replace actual email addresses and URLs and security tokens with fake strings.

Better yet, I'd prefer mock data be located in a module in https://github.com/Mirantis/lens-extension-cc/tree/master/test/mocks and imported instead of being set in a component like this.

2022-01-21 15:29 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +    },
This is technically a security breach as it is, since this PR is publicly posted on the repo for the entire world to see, and includes tokens that were actually valid at one point in time.

2022-01-21 15:43 UTC, AntonNos commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +    },
Fixed

2022-01-21 15:49 UTC, stefcameron commented on src/renderer/components/GlobalPage/SynchronizeBlock.js
> +export const SynchronizeBlock = ({ extCloud }) => {
Confirmed this will be handled in a future PR.

2022-01-21 15:49 UTC, stefcameron approved these changes
Good to merge! Thank you for your work on this.

2022-01-21 16:05 UTC, merged