PRODX-21180 Added ExtendedCloudProvider.js
Mirantis/lens-extension-cc pull request #683
Opened 2022-01-21 12:42 UTC by bnalisnikovskiy

WIP version ExtendedCloudProvider
 - load cloudStore.clouds - check them and create extendedClouds
 - update extendedClouds when cloudStore.clouds are changed (comparison based on `token`)
 - Update ExternalCloud additional data (namespaces, etc) each 5 min
 - Listen changes in ExternalCloud.namespaces

2022-01-21 17:03 UTC, stefcameron reviewed
This is looking good! 😄

2022-01-21 17:03 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    }
I don't think this is working as you're thinking. `pr.onChange()` will be called as soon as your loop is done here, but extended cloud objects will still be loading. `new ExtendedCloud(cloud)` will trigger the initial load in the next frame.

The only way to know when it's done is to add a listener for the LOADING_CHANGED event. So I would expect to see listeners added, and the `loadFinishedCount` counter increased for every call to the listener until the total is reached. Then you can set `pr.loading = false; pr.loaded = true; pr.onChange();`.

And I think we would never set `pr.error` because each ExtendedCloud has its own `error` property that users of `useExtendedCloud()` can check, so might be good to indicate that expectation with a comment so we remember we thought about `pr.error` and didn't just forget to set it to something.

2022-01-21 17:10 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    // when we update cloud - we update its token (for now at least, this 'compare' part may be changed in the future)
In this case `token` should suite well. We need to update (recreate) UI extendedCloud when cloud on disk is updated. Url stays the same, but we can't store cloud without `token` changes

2022-01-21 17:12 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    }
Yes, you are right. I had added this logic when we had `await extCloud.init()` separately, and in that case it worked well. I'll improve this

2022-01-25 21:14 UTC, stefcameron requested changes
This is going in the right direction, but I don't think those temporary counters should be getting persisted to disk...

2022-01-25 21:14 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    extCl.addEventListener(DATA_UPDATED, updateSingleCloud);
Because we just created the ExtendedCloud instance, we should be listening for the LOADING_CHANGED event, not DATA_UPDATED, so that we don't have added complexity of having to handle an as-yet unloaded EC object in `updateSingleCloud()`. Right now, it feels like there's still a hole in `updateSingleCloud()` when the EC isn't loaded yet.

2022-01-25 21:14 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    await cloud.loadConfig(); // we need to get config for getting namespaces and other at ExtendedCloud.init()
What if this promise fails? It'll cause the outer promise to fail, and that will cause an exception that will take down the whole app because it'll be an "unhandled rejected promise". I think it would also cause issues with the outer loop, possibly causing some or all other ExtendedClouds to fail to be created.

Also, calling `cloud.loadConfig()` here also feels like a detail that doesn't belong here where we're dealing with ExtendedClouds not Clouds. I think `ExtendedCloud#init()` should, internally, call `await this.cloud.loadConfig()` (with a `try/catch` in case it fails), which, in turn, would internally check if it's config is already loaded and just do nothing, or actually load the config.

Finally, I noticed `ExtendedCloud#init()` has a `loadAll` parameter: Do we need that parameter? Given we create an `ExtendedCloud` with a `Cloud` object, that that the `Cloud` instance has a property that tells us if all namespaces are synced, or only select ones, shouldn't what we load in `EC#init()` be dependent upon `this.cloud.syncAll` instead? Besides, when we create a new EC instance, we call `setTimeout(() => this.init());` which means we always initialize with `loadAll === undefined`, which isn't correct.

2022-01-26 08:01 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +      cloudsToUpdateCount: 0,
We are not storing them on the disk. `ExtendedCloudProviderStore` is local (UI) storage. Probably we won't need this at all, not sure if general `loading`, `loaded` will be useful, since we observe each ExtendedCloud and it has its own loader

2022-01-26 08:03 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +  pr.store.cloudsToUpdateCount = cloudUrls.length;
We don't persist them. It's only UI part to inform us when all `cloudUrlsToUpdate` are loaded

2022-01-26 10:54 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +      cloudsToUpdateCount: 0,
Update: I decided to remove them at all. I don't think we need 'loaders' for full clouds list. If we want we can listen each cloud separately and show loaders for particular ones

2022-01-26 11:10 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    extCl.addEventListener(DATA_UPDATED, updateSingleCloud);
It depends what we want. As we discussed [here](https://github.com/Mirantis/lens-extension-cc/pull/671#discussion_r788930269) in this place I follow `namespaces` updates only (without loading changes). 
However, if we want to show loader, better to use `LOADING_CHANGED`,  you are right

2022-01-26 17:34 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +  pr.store.cloudsToUpdateCount = cloudUrls.length;
You're right, my mistake in thinking these were getting stored to disk. Sorry for that confusion. But it sounds like you've removed them and the loading/loaded/error too, which I think is good.

2022-01-26 17:43 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    extCl.addEventListener(DATA_UPDATED, updateSingleCloud);
In my mind, because we're adding the event listener right after creating the EC instance, and then as soon as we're notified, we remove it, what we're really listening for is the initial load, which is `LOADING_CHANGED`. That was more intuitive to me than `DATA_UPDATED`, though I suppose the end-result, from the provider's perspective, is probably the same with either event.

2022-01-26 17:48 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    extCl.addEventListener(DATA_UPDATED, updateSingleCloud);
I tried both and `LOADING_CHANGED` works better.

2022-01-26 18:08 UTC, stefcameron approved these changes
Looking good! Some questions, but I don't think they're blocking issues. They could be handled in a subsequent PR, or here, or maybe you have different opinion. 🙂

2022-01-26 18:08 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
Do you think that at this point, we should now remove the LOADING_CHANGED listener, and add a listener for DATA_UPDATED? That listener would be `updateSingleCloud()` again. Just now triggering a context update (via `pr.onChange()`) to the ExtendedCloudProvider whenever an EC is updated. Or maybe this will result in too context updates (and so reloads of the SyncView), which would hurt performance, and so the SyncView should be the one to subscribe to individual ECs?

2022-01-26 19:06 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
If we want to show loader for single clouds, we should use `LOADING_CHANGED`. Technically, we don't rewrite Cloud (ref leads to the same object, but I'l double check) - so we shouldn't remove/update listeners. Or, maybe, I don't fully understand the comment...

2022-01-26 19:15 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
The side effect of `pr.onChange()` is that it will cause a change to the value provided by the context provider. That means that any piece of the UI that calls `useExtendedClouds()` to get the list of EC objects will get re-rendered.

The way you've coded this right now, because ECs load async over time, let's say we have 4 ECs, there will likely be 4 re-render cycles of all components that `useExtendedClouds()` as each EC finishes loading (in the case where they just end-up finishing serially, one after another).

That might negatively affect performance. If the list of ECs has not changed, we shouldn't `pr.onChange()`. We should only `pr.onChange()` when the list changes (an EC is added or removed completely).

So `pr.onChange()` should be called in `_loadData()` __once__ after the `cloudUrls` have been processed to notify users of the context provider that the list has changed in some significant way. That means that this statement should move down, just __after__ the `cloudUrls.forEach()` loop: https://github.com/Mirantis/lens-extension-cc/pull/683/files#diff-5ab31a3171545a614baaf23b1e4a69562bdc11a96a322c54e42c1ff591951f02R81

Then each view that `useExtendedClouds()` will get updated only when there's a significant change to the list of ECs that it provides, and from there, each view is responsible to add its own event listeners (for LOADING_CHANGE and/or DATA_UPDATED) on each EC in order to show a loader and update its UI.

In this way, we have a single provider for all ECs, but then each EC is treated individually.

2022-01-27 09:26 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
Okay. Let's think how it would work. We can call pr.onChange() in `_loadData` below forEach loop. 
`_loadData` happens in two cases: Initial load, and when `token` in Clouds is updated (our `updateTokens()` call). But if in ExtedndedCloud.init() method (each 5 min) we get new namespaces, with different count of sshKeys/credentials/etc `_loadData` won't be called. 
We can add listeners on component level (if I got your idea correctly) for each ExtendedCloud and show loader etc, but in this case we will have two source of truth. ExtendedClouds from `ExtendedCloudProvider` (outdated) and particular ExtendedCloud in component with new data. So here two ways: we need to update `ExtendedCloudProvider` from component somehow (and use it as one source of truth) or wait until new data come with next `_loadData` call (it happens each ~20 min, for one cloud, as I can see). 
 I don't think that's good approach

About possible performance issues. React optimized its strategy and comparison mechanism very good. If keys stay the same rendering takes very small time, we shouldn't afraid of that. Also we could look to some libraries, like 'reselect', to have memorized data, etc

2022-01-27 09:35 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    if (!extCl.cloud.token || extCl.cloud.isRefreshTokenExpired()) {
In `isValid` we also check `username`. If it's a required field and it always has to be setted, than `isValid` suits better

2022-01-27 15:47 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    if (!extCl.cloud.token || extCl.cloud.isRefreshTokenExpired()) {
We might be able to remove `username` from the check. It's not required in terms of being "connected" because all the API calls are done using tokens, not username/password with basic auth.

The `username` property is required (i.e. very important), however, for purposes of creating kubeconfig files that Lens will consume in order to add clusters.

I think `isConnected()` would be more intuitive when reading the code, and we can remove the `username` check inside of it so that the check is purely related to having tokens that are valid.

2022-01-27 16:57 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    if (!extCl.cloud.token || extCl.cloud.isRefreshTokenExpired()) {
I don't think we need a separate method. I think we can just rename `isValid` to `isConnected` and remove the `username` check inside of it. I was just explaining how the `username` is still an important piece of data, but it's not necessary in terms of connecting to the Cloud via API, so doesn't need to be in that check anymore. It's a relic from when this was the `AuthAccess` class.

2022-01-27 17:01 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
Can you point me to docs on `reselect`? I don't know about it (or don't remember it).

2022-01-27 17:02 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
https://github.com/reduxjs/reselect

2022-01-27 19:58 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
> I think I might create selector which takes 'url' and returns only one cloud when it's changed. So we might listen separately each cloud in their own 'row' components instead of connecting it through `useExtendedCloudData` on parent.

Will that also address the scenario where the number of ECs changes?.

The SyncView would do something like this with the provider:

```javascript
const { extendedClouds } = useExtendedClouds();
...
return (
  <List>
    {Object.values(extendedClouds).map((ec) => <SynchronizeBlock extendedCloud={ec} />)}
  </List>
);
```

Now you could use `reselect` and create a selector that reacts to changes to individual items within that map, so that would result in each SynchronizeBlock updating itself whenever the token expires and we get a new one. At the same time, though, `_loadData()` will run and will call `pr.onChange()` and then the SyncView itself will re-render, re-creating all the SynchronizeBlock instances anyway. So what benefit is there to the selector?

I don't see how we can improve performance other than to create an optimization in `_loadData()` where we don't create new EC instances if we already have them, but rather get them to update their data.

In the case where there are no new Clouds, and no old Clouds removed (the code isn't covering this case, BTW), but just new tokens for existing Clouds, ECs should just update their data, and SynchronizeBlock component instances should be listening to their respective EC's DATA_UPDATED event and refresh the UI when data changes. `_loadData()` should not call `pr.onChange()` in this case, and this will avoid SyncView getting re-rendered without cause.

There's still just one source of truth there about what the ECs are: The ExtendedCloudProvider.

In the case where a new Cloud is added, or an existing one is removed -- which means the number of ECs will change -- then `_loadData()` needs to detect that and call `pr.onChange()`. Also, in the case where a Cloud was removed, we don't need to call `_loadData()` (nothing to load). We just need to `delete pr.store.extendedClouds[url]` and remove the token also, and then call `pr.onChange()`.

Adding/removing Clouds should be an infrequent action. Clouds and ECs getting updated will happen all the time. We should make sure that's optimized.

2022-01-27 20:03 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +  cloudUrls.forEach(async (url) => {
Where are we handling the case where a Cloud has been removed? AFAICT, a removed Cloud would get removed from the `cloudStore` but would remain forever in the `extendedClouds` map as an EC instance that would keep getting rendered. We're missing a `delete pr.store.extendedClouds[url]` somewhere...

2022-01-27 21:37 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    pr.onChange();
I'll make a test branch tomorrow and show what I mean. In my view, with that optimization we almost shouldn't change a logic. Only in remove part, you are right about it, I need to test that better.

2022-01-27 21:41 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +  cloudUrls.forEach(async (url) => {
When cloud is removed it triggers `_loadData` and we load only existing clouds to ECProvider. But you're right in point that we don't need load data for clouds which left. I'll figure out how to do that in efficient way and avoid extra calls. Good point

2022-01-28 15:26 UTC, stefcameron approved these changes
The latest updates look good. We just need to optimize the case where an existing Cloud (for which we already have an EC in the provider) is updated: Update the existing EC (eventually resulting in the EC firing its DATA_UPDATED event) rather than create a new instance, and don't fire `pr.onChange()` if all that was done in `_loadData()` was to update existing ECs. Also don't fire `pr.onChange()` whenever an EC has been updated. Let each "consumer" of an EC add its own DATA_UPDATED and/or LOADING_CHANGED listener, as appropriate.

You can optimize this in a follow-up PR if you want. This PR should work as-is for now.

2022-01-28 18:05 UTC, stefcameron commented on src/common/ExtendedCloud.js
> +          this.dispatchEvent(EXTENDED_CLOUD_EVENTS.DATA_UPDATED, this);
I don't think we should be firing this event when the Cloud itself changes. The data hasn't changed at this point. We should be calling `this.init()` -- which we should rename to something like `updateData()` or `fetchData()` because it's weird to be calling `init()` every 5 minutes to do a data update... We're no longer initializing anything at that point.

2022-01-28 18:36 UTC, stefcameron approved these changes
Looks good again!

2022-01-31 06:48 UTC, merged