[PRODX-21176] Enable opening clusters in Lens based on context
Mirantis/lens-extension-cc pull request #692
Opened 2022-01-25 18:58 UTC by stefcameron

When manually adding a cluster from MCC into Lens via downloaded
kubeconfig, Lens generates its own UID for the cluster since the
UID isn't given in the kubeconfig. That means we can't search
by UID when opening a cluster from MCC in the browser that
wasn't added via the extension.

This changes to searching by the same context name that MCC generates
in its kubeconfigs. So now we can find any cluster, whether it was
manually added, or added via the extension.

2022-01-25 18:59 UTC, stefcameron commented
Note I also fixed-up a couple of mix-ups that happened related to the "activate cluster" protocol event during the recent clean-up (i.e. removal of "add to lens" support) and consolidated all things related to extension events into the eventBus.

2022-01-25 19:01 UTC, stefcameron commented
Also note this "ports" the feature originally added to the v3 maintenance branch into the new code: https://github.com/Mirantis/lens-extension-cc/pull/691

2022-01-26 11:47 UTC, bnalisnikovskiy requested changes
It looks good. Only one question about `EXT_EVENT_OAUTH_CODE`
We moved it from EventBus to avoid  circular dependency: eventBus -> Cloud -> ssoUtil -> AuthClient -> eventBus 
Check please this moment
![image](https://user-images.githubusercontent.com/95434160/151157858-35a163ea-be99-42b7-ace2-dbceb70ef591.png)

2022-01-26 18:32 UTC, stefcameron commented
> It looks good. Only one question about `EXT_EVENT_OAUTH_CODE` We moved it from EventBus to avoid circular dependency: eventBus -> Cloud -> ssoUtil -> AuthClient -> eventBus Check please this moment We discussed it [here in Slack](https://miracloud.slack.com/archives/D02PHAV9FAQ/p1641487755036100)

Oh, yes, we did. But it seems the circular dependency isn't there anymore because I tested this in Lens. The extension loads fine. `eventBus` no longer has any imports except for `rtvjs`, so whatever it was importing from `Cloud`, it no longer needs.

2022-01-26 19:43 UTC, bnalisnikovskiy approved these changes

2022-01-27 15:42 UTC, merged