WIP [PRODX-20981]: added clusters table
Mirantis/lens-extension-cc pull request #693
Opened 2022-01-26 15:26 UTC by AntonNos

2022-01-26 15:56 UTC, bnalisnikovskiy requested changes

2022-01-26 15:56 UTC, bnalisnikovskiy commented on src/renderer/components/EnhancedTable/EnhancedTable.js
> +function stableSort(array, comparator) {
we don't need IE support ;)

2022-01-26 18:36 UTC, stefcameron commented on src/renderer/components/EnhancedTable/EnhancedTable.js
> +function stableSort(array, comparator) {
IE 😱 !!!!

2022-01-26 18:43 UTC, stefcameron commented on src/renderer/components/GlobalPage/ManagementClusters.js
> +import styled from '@emotion/styled';
This component is what the existing `SyncView` should become. We should replace what's in `SyncView` with this instead of creating a new component here. Just delete everything that's in SyncView and replace it with this content -- except maybe https://github.com/Mirantis/lens-extension-cc/blob/master/src/renderer/components/GlobalPage/SyncView.js#L346-L349 if we still need a hacky way to show that wizard for the time being. FYI @bnalisnikovskiy

2022-01-26 18:45 UTC, stefcameron reviewed
Also, we're adding a new dependency on `@material-ui` but this PR doesn't include changes to the package.json nor to the lock file.

2022-01-27 20:34 UTC, AntonNos commented on src/renderer/components/EnhancedTable/EnhancedTable.js
> +function stableSort(array, comparator) {
Removed it:) Will add sorting in another PR, because we will have release in Feb, and I can't block Bogdan with this table

2022-01-27 22:27 UTC, stefcameron commented on src/renderer/components/GlobalPage/ManagementClusters.js
> +import styled from '@emotion/styled';
@AntonNos Do you plan on putting this code into the SyncView? We don't need this ManagementClusters view. This _is_ what the SyncView is supposed to display. 🙂

2022-01-28 07:13 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/ManagementClusters.js
> +import styled from '@emotion/styled';
I'll do that in my next PR. I already have a workpiece for that. In SyncView we should use Welcome, Connection, pages as well. So better do that all at once

2022-01-28 10:07 UTC, bnalisnikovskiy requested changes
Looks good, but need a few improvements

2022-01-28 10:07 UTC, bnalisnikovskiy commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +          <div style={{ display: 'contents' }} key={namespace.name}>
inline style

2022-01-28 10:07 UTC, bnalisnikovskiy commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +const EnhTableCell = styled.td`
I see that we have 4 `EnhTableCell` declaration in different files. Probably some of them could be renamed more specific...

2022-01-28 10:07 UTC, bnalisnikovskiy commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +              <EnhTableCell></EnhTableCell>
just FYI, we can use shorter form `<EnhTableCell />` if component is empty. Eslint even has rule for that, obviously, we have it turned off 
No changes is required here. Up to you

2022-01-28 12:27 UTC, bnalisnikovskiy approved these changes
Looks good. I think It's ready to merge. Other additional features (like sorting) or possible bugs may be fixed in separate tickets

2022-01-28 16:55 UTC, merged