Optimize ExtendedCloud data fetches, fix bugs
Mirantis/lens-extension-cc pull request #711
Opened 2022-02-05 01:22 UTC by stefcameron

There was too much churn when fetching data for an ExtendedCloud:
Duplicated requests, multiple parallel data fetches for the same
EC, and too much back and forth between the CloudStore and the
ExtendedCloudProvider whenever a Cloud would get updated with
new tokens after they would get refreshed.

I fixed and changed a number of things. Here's a list of the most
prominent issues I addressed:

- addEventListener() in Cloud and EC was immediately calling the event
  handler instead of adding it to the list of handlers.
- Cloud didn't have enough events. Just having the one DATA_UPDATED
  event for all property changes was resulting in the EC using that
  Cloud to get notified (and trigger a data fetch) much too often.
  The EC only needs to fetch new data if the Cloud's sync-related
  properties change. Nothing else.
- Only the CloudStore is interested in all possible Cloud property
  changes so it can persist it to disk.
- When the EC's `cloud` property is updated from the
  ExtendedCloudProvider, the Cloud object actually isn't new, so
  there's no need to trigger a data fetch whenever the property
  is set. Now we check to see if the new value is actually
  different.
- When updating the EC's `cloud` property to a new Cloud, we
  weren't checking to see if we already had a Cloud object
  and removing listeners.
- Delaying the data fetch internally within the EC using the
  event dispatching mechanism is a good way to de-duplicate
  data fetch requests, rather than imperatively making them.
- Cloud.idpClientId was not needed, removed.
- The AddCloudInstance component was not properly destroying
  the temporary EC instance it was creating, which created a memory
  leak, and a random EC that kept fetching data after the
  component was unmounted ("destroyed" meaning event listeners
  on the Cloud removed, and interval stopped).
- In EC.fetchData(), we were continuing with requests to load
  clusters and ssh keys even though a previous request had
  failed, which would ultimately result in discarding the data
  and setting EC.error instead, so now we don't pursue additional
  unnecessary requests.
- authUtil module now returns an additional `tokensRefreshed`
  property in its payload, indicating whether tokens were
  refreshed as part of making the request. Turns out there's
  no optimization to make with this now that the EC doesn't
  care if the Cloud's tokens get updated, but this is handy
  nonetheless, so I left it in place.
- CloudStore was leaking Clouds when it would get reloaded
  from disk (Lens does sync to the disk every now and then,
  so even while Lens is running, we can get a random read
  from disk, causing us to overwrite the existing `clouds`
  map). We don't support this, so now we just skip resetting
  the `clouds` map when it's already set. If you want to
  mess with the JSON file on disk, quit Lens, mess with
  it, and then restart Lens.

2022-02-05 01:24 UTC, stefcameron commented
__NOTE__: In case you guys ask me to make some changes, I left all my `console` debugging statements in place. 😄 

👉 All statements that have a `// DEBUG LOG` or `// DEBUG REMOVE` comment after them __will be removed__ before I merge. (They'll cause the build to break too, since `// DEBUG` results in a linting error.)

2022-02-05 01:25 UTC, stefcameron commented
And there is one issue that I've asked the Lens team for help on, which is that, at least for me, Lens is no longer writing data to the `cloud-store.json` file on disk, even though we're generating valid JSON for it. No idea why.

2022-02-07 09:26 UTC, bnalisnikovskiy commented
Seems we have a problem with store-on-disk. When I add new Cloud, after 'Synchronize Selected click' I redirected to SyncView and it appears in the table (all is good), but cloud-store.json doesn't have that cloud.

2022-02-07 10:37 UTC, bnalisnikovskiy requested changes
A few comments/questions 
+ store on disk isn't working for me

2022-02-07 10:37 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +  return { newUrls, updatedUrls, oldUrls };
I see a few gaps in this `_triageCloudUrls` function.  On line 50 you check  `if(currentTokens[storeUrl])` but it's  not a `updatedUrls` we push all clouds present in `storeTokens` to  `updatedUrls`. We need compare tokens inside and only then push url (if needed). I implemented that check on line 167 in `reduce` to avoid one more iteration.

2022-02-07 10:37 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +    });
As a variant, with less iterations count 
``` 
Object.keys(currentTokens).forEach((url) => {
    if(storeTokens[url]) {
      updatedUrls.push(url); // note that this is not actual updated cloud. Just an existing one. We don't check tockens inside 
    } else {
      newUrls.push(url)
    }
    })
  const oldUrls = Object(_.omit(storeTokens, updatedUrls) || {}).keys
```

2022-02-07 10:37 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
>      const cloudUrlsToUpdate = [];
we don't use this anymore (probably should?)

2022-02-07 10:37 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +  cloudsUrlsToDelete
Nitpick. Better to use Object as argument if arguments.count > 3. Just to avoid order-bugs

2022-02-07 10:37 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +  cloudUrlsToAdd.concat(cloudUrlsToUpdate).forEach((url) => {
We always iterate all clouds, even if token still the same.  `cloudUrlsToUpdate` contains all existing clouds (see other comments)

2022-02-07 10:37 UTC, bnalisnikovskiy commented on src/store/CloudStore.js
> +    Object.values(CLOUD_EVENTS).forEach((eventName) =>
Do we need listen `STATUS_CHANGE` on this level?

2022-02-07 14:49 UTC, stefcameron commented
> Seems we have a problem with store-on-disk. When I add new Cloud, after 'Synchronize Selected click' I redirected to SyncView and it appears in the table (all is good), but cloud-store.json doesn't have that cloud.

Yes, I'm aware of that. I have the same problem too, and no idea what's going on. I've spent a lot of time scratching my head. I'm hoping someone from the Lens team will help me figure it out before I merge this.

2022-02-07 14:51 UTC, stefcameron commented on src/common/ExtendedCloud.js
>      this._updateInterval = setInterval(() => {
It's not doing any harm. Whether we need to have the interval or not, the EC still needs to be properly destroyed by AddCloudInstance because the EC, at the least, listens to the Cloud internally.

2022-02-07 15:44 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +    });
Thanks for the suggestion, but I don't think this saves a loop because you're looping once with `Object.keys(currentTokens)` and then another time with `_.omit(...)`. In the worst case scenario, the length of `currentTokens` is equal to that of `storeTokens`.

2022-02-07 15:45 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +  return { newUrls, updatedUrls, oldUrls };
Thanks for mentioning this! I see that comparison now, and that piece of code is actually no longer being used. I'm reworking this a bit to clean it up.

2022-02-07 15:45 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
>      const cloudUrlsToUpdate = [];
Right! Related to https://github.com/Mirantis/lens-extension-cc/pull/711#discussion_r800496150

2022-02-07 15:46 UTC, stefcameron commented on src/renderer/store/ExtendedCloudProvider.js
> +  cloudUrlsToAdd.concat(cloudUrlsToUpdate).forEach((url) => {
Right! Related to https://github.com/Mirantis/lens-extension-cc/pull/711#discussion_r800496150

2022-02-07 17:05 UTC, bnalisnikovskiy commented on src/renderer/store/ExtendedCloudProvider.js
> +  return { newUrls, updatedUrls, oldUrls };
Looks good now.
Waiting for store-on-disk fix and after testing I can approve that. Hard to say what can goes wrong right now. I spent almost full day on testing and  checking this feature at first realisation :)

2022-02-07 22:42 UTC, stefcameron commented
@bnalisnikovskiy The changes in https://github.com/Mirantis/lens-extension-cc/pull/711/commits/646f667f4e7fa914fa066e1cee0769033d307c95 fix the CloudStore disk issue.

2022-02-08 11:56 UTC, bnalisnikovskiy approved these changes
LGTM! CloudStore works well. Can be merged after console.log clean up

2022-02-08 21:16 UTC, merged