WIP PRODX-21692 WIP: Added Credentials
Mirantis/lens-extension-cc pull request #725
Opened 2022-02-09 14:13 UTC by bnalisnikovskiy

WIP version. Just for discuss problems and find better ways

2022-02-09 20:12 UTC, stefcameron commented
I noticed this PR, but I believe you posted it before I updated the info in the ticket, so I'll wait for you to update the code.

2022-02-11 14:53 UTC, bnalisnikovskiy commented on src/renderer/store/Credential.js
> +    this.labels = [];
FYI @stefcameron 
Regarding to design we need next fields: 
- Status
- Source ('MCC')
- labels 
Currently, I don't know where we can take it. This has to be updated for each class. 
<img width="381" alt="image" src="https://user-images.githubusercontent.com/95434160/153613758-4e813b05-1c3d-4309-99c7-f2b761e920f4.png">

2022-02-11 16:53 UTC, stefcameron commented on src/renderer/store/Credential.js
> +    this.labels = [];
These three properties are "presentation" properties related to the Catalog Entity that will use a class instance such as `SshKey` or `Cluster` for its data.

So in my view, `source` (which will always be the string "MCC"), `status`, and `labels` belong in the related entity (for an `SshKey` instance, that will be the `SshKeyEntity`, and as an example, `status` is determined here: https://github.com/Mirantis/lens-extension-cc/blob/master/src/catalog/SshKeyEntity.ts#L19).

For the labels, we know what they will be based on each entity type, and when we [add entities to the Catalog](https://github.com/Mirantis/lens-extension-cc/blob/master/src/main/IpcMain.js#L238), we will generate labels for them based on the underlying class' properties. I'm not doing that for the fake items, but you can see that the generic [entity model metadata](https://github.com/Mirantis/lens-extension-cc/blob/master/src/typesets.js#L18) defines a `labels` property, so every Catalog entity has labels.

For example, a [CredentialEntity](https://github.com/Mirantis/lens-extension-cc/blob/master/src/catalog/CredentialEntity.ts) will get 2 labels: "project" and "managementCluster". The `SyncManager` -- who will be the thing that creates and adds these entities to the Catalog -- should be able to look at a `Credential` class instance and determine what it's namespace (i.e. "project") is, as well as what it's mgmt cluster (i.e. the `ExtendedCloud`) to which it belongs (and then it's a matter of `credential.extendedCloud.cloud.name` for the mgmt cluster label's value).

Also, looking into this made me remember that I had already figured out the basis of the models for most entity types here:

- https://github.com/Mirantis/lens-extension-cc/blob/master/src/typesets.js#L55
- https://github.com/Mirantis/lens-extension-cc/blob/master/src/typesets.js#L81
- https://github.com/Mirantis/lens-extension-cc/blob/master/src/typesets.js#L103
- https://github.com/Mirantis/lens-extension-cc/blob/master/src/typesets.js#L128

Just missing License. I'm sorry I forgot to mention this earlier. I did the Catalog entity work back in December before I went on Christmas vacation.

2022-02-11 18:16 UTC, stefcameron requested changes
Just minor changes. After we merge this, I'll do a second pass to reconcile gaps I've now identified between this work (that we need) and the initial discovery work I did for catalog entities in https://github.com/Mirantis/lens-extension-cc/tree/master/src/catalog

2022-02-11 18:16 UTC, stefcameron commented on src/renderer/store/Credential.js
> +  constructor(data, namespace) {
The constructor should take another parameter that is the credential type, which should be one of the `credentialTypes` values.

2022-02-11 18:16 UTC, stefcameron commented on src/renderer/store/Namespace.js
>            _sshKeys = newValue || null;
Default to `[]`

2022-02-11 18:16 UTC, stefcameron commented on src/renderer/store/Namespace.js
>          }
Default to `[]`

2022-02-11 18:16 UTC, stefcameron commented on src/renderer/store/Namespace.js
> +     * @member {Array<Object>|null} proxies Proxies in this namespace. `null` if unknown.
"proxies" -> "licenses"

2022-02-11 18:16 UTC, stefcameron commented on src/renderer/store/Namespace.js
> +     * @member {Array<Object>|null} proxies Proxies in this namespace. `null` if unknown.
Should also be just `{Array<License>}` for the type.

2022-02-11 18:16 UTC, stefcameron commented on src/renderer/store/Namespace.js
> +    let _licenses = null;
I think it'll be better for downstream code if we ensure that these properties are always arrays, and empty if none/unknown. If we don't know what they are, that's because we haven't fetched the namespace, and we won't have a Namespace class instance in that case anyway.

```suggestion
    let _clusters = [];
    let _sshKeys = [];
    let _credentials = [];
    let _proxies = [];
    let _licenses = [];
```

2022-02-11 18:16 UTC, stefcameron commented on src/renderer/store/SshKey.js
> +    this.labels = [];
Can be removed.

2022-02-14 14:21 UTC, stefcameron approved these changes
Thanks for those updates!

Looks good. Just maybe we should rethink the `Namespace.credentials` property. See my comment and let me know what you think about it.

2022-02-14 14:47 UTC, bnalisnikovskiy commented on src/renderer/store/Namespace.js
> +     * @param {number} credentials.allCredentialsCount
Thanks for your comment. I'll improve JSDoc as you said. As I can see, Webstorm doesn't handle them so well as VSCode does

About credentials structure, it sounds good and simple structure looks preferred. Only one thing I worried about is body response. We do three different API calls for them, so maybe `response.body` has some major diversities, it's hard to predict without real data/description (what to expect). 

I event don't know what is better on current stage, keep them as it is for now, or change to single mixed-types array hoping that data signature the same...

2022-02-14 15:18 UTC, bnalisnikovskiy commented on src/renderer/store/Namespace.js
> +     * @param {number} credentials.allCredentialsCount
Updated

2022-02-14 15:22 UTC, stefcameron approved these changes
Looks good!

2022-02-14 15:28 UTC, merged

2022-02-18 18:02 UTC, stefcameron commented on src/renderer/store/Credential.js
> +    this.labels = [];
Addressed in #743 and #744