[PRODX-21648]: added remove cloud logic
Mirantis/lens-extension-cc pull request #728
Opened 2022-02-09 21:14 UTC by AntonNos

2022-02-09 22:59 UTC, stefcameron requested changes
Finally, the remove option! That will help with local testing... 😄

2022-02-09 22:59 UTC, stefcameron commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +          extendedCloud.destroy();
We shouldn't call this directly. Removing it from the CloudStore will result in the EC being automatically destroyed by the ExtendedCloudProvider.

2022-02-09 22:59 UTC, stefcameron commented on src/strings.ts
> +        `Are you sure you want to remove the <b>${cloudName}</b> cloud from Lens?`,
```suggestion
        `Are you sure you want to remove the <b>${cloudName}</b> Management Cluster from Lens?`,
```

2022-02-10 13:50 UTC, bnalisnikovskiy approved these changes
Looks good. One nitpick

2022-02-10 13:50 UTC, bnalisnikovskiy commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +    title: `${contextMenus.cloud.remove()}`,
NIt: Just `contextMenus.cloud.remove()` without ``${}``

2022-02-11 10:36 UTC, AntonNos commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +          />
There is one more question - what should we do if management cluster is `disconnected`? For now, I removing it without any dialog message. Is it okay, or should we fetch data and also show the following projects and their associated catalog items?

2022-02-11 14:54 UTC, stefcameron commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +          />
Good question. If the Cloud is disconnected, we may (likely) have connected to it at least once and synced entities into Lens, so these entities will still get removed. But if Lens starts with the Cloud disconnected, we won't know what all the projects are -- if they're syncing all projects. If they're syncing specific projects, we can get the list from `extendedCloud.cloud.syncedNamespaces`.

So if `!cloud.connected` OR `!extendedCloud.loaded`, then
- if `!cloud.syncAll`, use `cloud.syncedNamespaces` to list the projects in the confirmation dialog (this list must have at least one name in it)
- if `cloud.syncAll`, use the same message, except don't show the list of projects (and replace "items:" with "items." -- a period instead of a colon) because we don't know what they are.

Else (which means `cloud.connected` AND `extendedCloud.loaded`), then `extendedCloud.syncedNamespaces` should be the list of projects whose items will be removed:
- if `syncedNamespaces.length > 0`, show the message with the project names in bullet points.
- if `syncedNamespaces.length <= 0`, don't show the confirmation dialog at all; there are no namespaces, so no items in the Catalog related to them, so nothing will be lost if the Cloud is removed.

I think that should cover all the cases. Can you think of any others?

2022-02-14 15:28 UTC, stefcameron commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +        if (extendedCloud.cloud.syncNamespaces > 0) {
You have a bug here, missing `.length` on the array.

BUT: It might be safer in the long run to also check that we aren't syncing all namespaces. But then to go further, given that in this `else` block, we're both connected AND loaded, the even-safer check would probably be `if (extendedCloud.namespaces.length > 0)` because given we're connected and loaded, if that list is empty, we can be sure that there are no namespaces _being_ synced (whether `Cloud.syncAll` is true or `Cloud.syncNamespaces.length > 0`).

2022-02-14 15:28 UTC, stefcameron commented on src/strings.ts
> +              .map((project) => `<li>- ${project}</li>`)
We don't need the hyphen here; the `<li>` will provide a bullet already.

Could you post a screenshot of this dialog when there's a list and when there isn't?

2022-02-14 20:23 UTC, AntonNos commented on src/strings.ts
> +              .map((project) => `<li>- ${project}</li>`)
Screenshots was added to description.

2022-02-14 20:25 UTC, AntonNos commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +        if (extendedCloud.cloud.syncNamespaces > 0) {
Yes, thanks for letting me know, that I missed `.length`.

2022-02-15 01:02 UTC, stefcameron approved these changes
This will work! Just one last thing to tweak before you merge:

![image](https://user-images.githubusercontent.com/2855350/153972750-7baa0cb1-65e5-4d7b-b82d-d1e40b621eea.png)

Can you add an empty line between the two paragraphs in this case?

2022-02-15 09:40 UTC, merged