[PRODX-21534]: added spinner to AddCloudInstabce component
Mirantis/lens-extension-cc pull request #730
Opened 2022-02-10 13:35 UTC by AntonNos

![Screenshot 2022-02-10 at 15 33 51](https://user-images.githubusercontent.com/33761040/153418873-c80f64df-ef7e-4784-b4b3-3c3d86a5b54d.png)

2022-02-10 16:20 UTC, stefcameron requested changes
This is good, but the spinner isn't covering the full span of the async workflow. As soon as the user clicks on the Connect button, and the button gets disabled, the spinner should be visible right up until the moment where we display the list of projects.

2022-02-11 12:40 UTC, AntonNos commented
> While we're at it, please also test the error case (i.e. what happens if `Cloud.connect()` or `ExtendedCloud.fetchData()` fails. We need to make sure we have good error handling and show an error message to the user. Probably something like, "An error occurred while connecting to the management cluster and retrieving its projects. Click on the Connect button to try again."

Thank you for suggesting that need to add an error message. I attached screenshot how it looks.

2022-02-11 13:03 UTC, bnalisnikovskiy requested changes

2022-02-11 13:03 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/ConnectionBlock.js
> +    managementClusterName
we don't need this arguments. You can use them directly 
```
const handleConnectClick = () => {
    setShowInfoBox(false);
     handleClusterConnect(clusterUrl, clusterName);
  };
  ```

2022-02-11 13:03 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/ConnectionBlock.js
> +          disabled={extCloudLoading}
Now it's not only `extCloudLoading`, so lets rename it to `loading`

2022-02-11 13:03 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/ConnectionBlock.js
> +              handleConnectClick(clusterUrl, setClusterUrl, clusterName)
we don't need arguments. See comment above

2022-02-11 13:45 UTC, bnalisnikovskiy approved these changes
Looks good. One comment

2022-02-11 13:45 UTC, bnalisnikovskiy commented on src/renderer/components/GlobalPage/ConnectionBlock.js
> +            onClick={() => handleConnectClick()}
just `onClick={handleConnectClick}` in this case

2022-02-11 14:56 UTC, stefcameron commented
> > While we're at it, please also test the error case (i.e. what happens if `Cloud.connect()` or `ExtendedCloud.fetchData()` fails. We need to make sure we have good error handling and show an error message to the user. Probably something like, "An error occurred while connecting to the management cluster and retrieving its projects. Click on the Connect button to try again."
> 
> Thank you for suggesting that need to add an error message. I attached screenshot how it looks.

And thanks for adding! But I think we should make it an error notification instead of putting the error message in the UI. So the spinner should disappear, and the error notification should appear (Lens will show it in the top/right corner of the window). See https://github.com/Mirantis/lens-extension-cc/blob/master/src/renderer/renderer.tsx#L169 for an example.

2022-02-15 13:22 UTC, AntonNos commented
> > > While we're at it, please also test the error case (i.e. what happens if `Cloud.connect()` or `ExtendedCloud.fetchData()` fails. We need to make sure we have good error handling and show an error message to the user. Probably something like, "An error occurred while connecting to the management cluster and retrieving its projects. Click on the Connect button to try again."
> > 
> > 
> > Thank you for suggesting that need to add an error message. I attached screenshot how it looks.
> 
> And thanks for adding it! But I think we should make it an error notification instead of putting the error message in the UI. So the spinner should disappear, and the error notification should appear (Lens will show it in the top/right corner of the window). See https://github.com/Mirantis/lens-extension-cc/blob/master/src/renderer/renderer.tsx#L169 for an example.

Added error message to Notification instead of UI block

2022-02-15 17:37 UTC, stefcameron approved these changes
Thanks for changing it to an error notification!

2022-02-15 20:48 UTC, merged