PRODX-21857 Added one more status for EC.fetchingData
Mirantis/lens-extension-cc pull request #736
Opened 2022-02-15 13:36 UTC by bnalisnikovskiy

Since our Spinner component doesn't suite to the table, I added one more status 'Updating' during fetchingData event. 
In my opinion, spinner or animation would be better, but it's need more work from Lens/designers side. Open to proposals

Also we hide accordion arrow til we get namespaces (in first time)

<img width="809" alt="image" src="https://user-images.githubusercontent.com/95434160/154102759-66df958f-30ff-45e7-8dc5-4d98d74d1dec.png">

2022-02-15 15:54 UTC, stefcameron requested changes
Thanks for addressing these two issues!

So with this change, when Lens loads and there's a Cloud in storage, the status column will go from "Disconnected -> Connecting... -> Connected -> Updating... -> Connected", and then 5 minutes later, when we do a scheduled fetch of that Cloud's state, the status column will go from "Connected -> Updating... -> Connected"?

2022-02-15 15:54 UTC, stefcameron commented on src/strings.ts
>      connecting: () => 'Connecting',
I think it would be better if we had an ellipsis here, "Connecting..."

2022-02-15 15:54 UTC, stefcameron commented on src/strings.ts
> +    updating: () => 'Updating',
I don't think we should go to this level because we don't have per-namespace event notifications and syncing. We just fetch/sync at the cloud level. So for a namespace, the most important status is either "Synced" or "Not synced" based on the Cloud's status ("Disconnected" or not).

2022-02-15 16:11 UTC, bnalisnikovskiy commented
> Thanks for addressing these two issues!
> 
> So with this change, when Lens loads and there's a Cloud in storage, the status column will go from "Disconnected -> Connecting... -> Connected -> Updating... -> Connected", and then 5 minutes later, when we do a scheduled fetch of that Cloud's state, the status column will go from "Connected -> Updating... -> Connected"?

Yes. But after Connecting we see Updating without  'Connected' step. It's related to how and at what moment we get statuses from EC

2022-02-15 17:38 UTC, stefcameron approved these changes
Thanks for the updates! 👌

2022-02-15 21:44 UTC, stefcameron commented
Note that on Slack, there's a recommendation/expectation/assumption from John that "Disconnected" label is gray, not red. Could you update that before you merge? Use a gray from Lens that's bright enough that provides enough contrast so that the word is easily read.

2022-02-16 08:22 UTC, bnalisnikovskiy commented
> Note that on Slack, there's a recommendation/expectation/assumption from John that "Disconnected" label is gray, not red. Could you update that before you merge? Use a gray from Lens that's bright enough that provides enough contrast so that the word is easily read.

Changed to gray. Notice that in figma we have it red. Probably need to be updated. FYI @mgorczyca-mirantis

2022-02-16 08:51 UTC, merged