PRODX-21945 Fixed Selective sync UX issues
Mirantis/lens-extension-cc pull request #748
Opened 2022-02-18 17:52 UTC by bnalisnikovskiy

[Link to the ticket](https://mirantis.jira.com/browse/PRODX-21945)
Main changes: 
- Added 'Synchronize future projects' checkboxes for `syncAll` bool in SynchronizeBlock and in SelectiveSync Table
- Added `Cloud.ignoredNamespaces` where we store all unchecked projects
- Added logic to ExtendedCloud, which updates `Cloud.ignoredNamespaces`  and `Cloud.syncedNamespaces` in it got new project. Depending on `syncAll` we're choosing where to move new project ignored or synced
- Fixed issue when SelectiveSync table isn't updated after new data come (eg when Cloud disconnected=> we reconnect it and go to SelectiveSync view before EC.dataFetch is finished)

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/95434160/154734857-646c89aa-5156-4b15-bfd5-1c310c2c4705.png">
<img width="908" alt="image" src="https://user-images.githubusercontent.com/95434160/154734993-ebfd4228-ea17-4538-86bb-f3b2ee6e6e40.png">

2022-02-18 18:07 UTC, stefcameron commented
👀

2022-02-18 19:23 UTC, stefcameron requested changes
Nice work! You hit every nail on the head in the ticket except for a missing label. 🎉 I did some local testing and found a few issues when the Cloud is disconnected. See comments.

2022-02-18 19:23 UTC, stefcameron commented on src/renderer/components/hooks/useCheckboxes.js
>  };
Somewhere, not sure if it's here specifically, there's a few bugs when the Cloud is __disconnected__ and I'm going in/out of Selective Sync mode.

- First, when I'm in SyncView (not Selective Sync), I don't see the twisty with the list of synced namespaces (just without the cluster/cred/key counts):

![image](https://user-images.githubusercontent.com/2855350/154746176-127ae31b-7f53-4fbd-b8f2-5f06128f5829.png)

- Next, if I go into Selective Sync mode and simply toggle the `syncAll` flag from true to false (I uncheck it), I lose the entire list of `ignoredNamespaces` on the Cloud (and in the `cloud-store.json`).

- If I go into Selective Sync mode and uncheck a project and apply changes, it correctly moves into `ignoredNamespaces`. But if I also toggle the `syncAll` flag true or false, I will lose that whole list.

- If I uncheck all namespaces, so they all move to `ignoredNamespaces`, and then go back into Selective Sync view, I don't see any namespaces. When the Cloud is disconnected, we should show the full list of namespaces from `syncedNamespaces` and `ignoredNamespaces`, with them checked/unchecked, respectively.
    - Even though we're disconnected, we shouldn't forget about ignored namespaces -- especially if the user has `syncAll: true`. Otherwise, once we finally reconnect, we'll end-up auto-syncing all of the ones they deselected just minutes ago.
    - When we're disconnected, removing a namespace will cause items to disappear from the Catalog, which is fine.
    - When we're disconnected, adding a namespace will simply have no effect until the Cloud is reconnected again. The SyncManager will just do nothing (since `EC.syncedNamespaces` won't reflect that namespace until the Cloud is reconnected anyway).

- We're missing the "(Disconnected)" label next to the Cloud's name in Selective Sync view.

- If a Cloud doesn't have any namespaces, then the twisty shouldn't be visible in Selective Sync view like it is today:

![image](https://user-images.githubusercontent.com/2855350/154747294-953de56f-cd9b-44f1-95e8-82845e626956.png)

2022-02-18 19:23 UTC, stefcameron commented on src/strings.ts
> +      autosync: () => 'Autosync',
I know the mock-up shows "Autosync", but it should be "Auto-sync".

2022-02-18 19:23 UTC, stefcameron commented on src/strings.ts
> +  autoSync: () => 'auto-sync',
Let's capitalize it, "Auto-sync"

2022-02-21 10:48 UTC, bnalisnikovskiy commented on src/common/Cloud.js
> +    Object.defineProperty(this, 'updateNamespaces', {
Done

2022-02-21 10:52 UTC, bnalisnikovskiy commented on src/renderer/components/EnhancedTable/EnhancedTableRow.js
> +  namespaces: PropTypes.arrayOf(PropTypes.object).isRequired,
'namespaces' is always an object. It could be a class or just `{name: 'foo' }`. We make it in `TableRowListenerWrapper` => `getNamespaces`.
  Updated

2022-02-21 10:53 UTC, bnalisnikovskiy commented on src/renderer/components/hooks/useCheckboxes.js
>  };
Improved. I hope I cover all cases. 
Strange but I couldn't reproduce your issues with `syncAll` and empty `ignoredNamespaces`

2022-02-21 16:09 UTC, stefcameron commented on src/renderer/components/hooks/useCheckboxes.js
>  };
You got them all except the last one: In Selective Sync mode, when disconnected (though this may not make a difference; should test both connected and disconnected) and the Cloud does not have any namespaces (synced and ignored lists are both empty), the twisty is still visible (but you can't click it):

![image](https://user-images.githubusercontent.com/2855350/154991249-ee9d4939-d7c3-46e5-b0d0-0c593eccd0ed.png)

The twisty should be hidden in this case, because there's nothing to reveal related to the Cloud.

2022-02-21 16:12 UTC, stefcameron commented
One last thing (aside from the twisty issue I pointed out): We should always sort namespaces alphabetically based on name, with the exception of always putting the "default" namespace at the top of the list.

So if we had default, a-namespace, and some-namespace, they would be listed as:

- default
- a-namespace
- some-namespace

The default namespace is where MCC puts the mgmt cluster, so it's treated a little bit special. It always exists since it's the default namespace in Kubernetes.

Let's do this only when we present the namespaces in the UI (in components), not in Cloud or ExtendedCloud since they don't need them to be sorted.

2022-02-22 09:37 UTC, bnalisnikovskiy commented
Fixed last issue and added sorting for namespaces

2022-02-22 15:18 UTC, stefcameron commented on src/renderer/components/EnhancedTable/tableUtil.js
> +};
`String.includes()` does not do an exact match. We should look for the "default" namespace _exactly_, otherwise, the sort will get messed-up if a namespace includes the word "default". There can only be one "default" namespace.

Also, using `String.localeCompare()` might be safer than a straight numerical comparison.

So this could be as simple as:

```suggestion
const compareNamespaces = (first, second) => {
  if (first.name === 'default') {
    return -1;
  }

  if (second.name === 'default') {
    return 1;
  }

  return first.name.localeCompare(second.name);
};
```

2022-02-22 16:15 UTC, bnalisnikovskiy commented on src/renderer/components/EnhancedTable/tableUtil.js
> +};
I wasn't sure about 'default' thanks. Good point, about `localeCompare` appreciated

2022-02-22 18:28 UTC, stefcameron approved these changes
I think we've got it! Thanks for fixing all those bugs.

There's just 2 more little things, but no need to re-review, just merge after fixing. In Selective Sync view:

<img width="186" alt="Screen Shot 2022-02-22 at 12 19 45 PM" src="https://user-images.githubusercontent.com/2855350/155195559-c7c75ee0-af46-4622-a2d6-1af5ed528af4.png">

- [ ] When the Cloud is disconnected, the "(Disconnected)" label next to the name doesn't look right. Should be `asdf (Disconnected)` in the image above.
- [ ] If the Cloud doesn't have any namespaces to show, we've removed the twisty (which is good), but we should also make sure the checkbox (which would otherwise "select all/none" namespaces) is both disabled and unchecked. So it's still visible, just unchecked and you can't check it.

Once you merge this, we can declare steps 10 and 11 "done" and I'll post another alpha build to NPM for people to play with.

2022-02-23 08:41 UTC, merged