[PRODX-22247]: added open in browser functionality to catalog entities
Mirantis/lens-extension-cc pull request #768
Opened 2022-03-03 18:23 UTC by AntonNos

2022-03-03 18:51 UTC, stefcameron requested changes

2022-03-03 18:51 UTC, stefcameron commented on src/util/helper.js
> +  return `${metadata.cloudUrl}/${metadata.namespace}/type?name=${metadata.name}`;
Not quite. The URL isn't valid. Use your access to the internal MCC instance to figure out what the URL will be given the entity type.

Also, instead of a new generic "helper" module, let's put this method in `src/catalog/catalogEntities.js`

2022-03-03 18:51 UTC, stefcameron commented on src/catalog/CredentialEntity.ts
>              'opening Credential %s in browser...',
These placeholder log statements can be removed for each entity type.

2022-03-03 19:27 UTC, stefcameron commented on src/util/helper.js
> +  return `${metadata.cloudUrl}/${metadata.namespace}/type?name=${metadata.name}`;
Also, maybe you can use the enumeration values from https://github.com/Mirantis/lens-extension-cc/blob/master/src/api/apiConstants.js#L11 to help identify the entity for which you need a URL instead of creating another "entity types" list. So we'd have `generateEntityUrl(apiEntities.PUBLIC_KEY, entity)`.

Might also be good for this function to receive the full entity, not just its metadata.

2022-03-03 22:04 UTC, stefcameron commented on src/util/helper.js
> +  return `${metadata.cloudUrl}/${metadata.namespace}/type?name=${metadata.name}`;
I actually ended-up having to implement something that would help here, but it's still on #759 right now, which is that every Catalog entity will now have a `entity.metadata.kind` property, which will be one of the values in the new `apiKinds` enum, which is now defined in `/api/apiConstants.js` (see the file in the PR).

So with that, you wouldn't need to pass the kind in, because you'd already have it. We would just need to pass the Catalog entity into the function, like `generateEntityUrl(entity)`, and internally, you could compare `entity.metadata.kind` to one of the values in `apiKinds` and generate the correct URL based on that kind.

There is also `apiCredentialKinds` in `/api/apiConstants.js` which provides an enum of just the credentials (i.e. a subset of `apiKinds`), which could help to identify if the entity is some type of credential (the URL will be the same for any type of credential, except its name, of course).

2022-03-04 04:38 UTC, stefcameron commented on src/util/helper.js
> +  return `${metadata.cloudUrl}/${metadata.namespace}/type?name=${metadata.name}`;
This is now all on master: https://github.com/Mirantis/lens-extension-cc/blob/master/src/api/apiConstants.js#L56

2022-03-04 11:22 UTC, AntonNos commented on src/util/helper.js
> +  return `${metadata.cloudUrl}/${metadata.namespace}/type?name=${metadata.name}`;
> Also, maybe you can use the enumeration values from https://github.com/Mirantis/lens-extension-cc/blob/master/src/api/apiConstants.js#L11 to help identify the entity for which you need a URL instead of creating another "entity types" list. So we'd have `generateEntityUrl(apiEntities.PUBLIC_KEY, entity)`.
> 
> Might also be good for this function to receive the full entity, not just its metadata.

Thanks Stefan, I fixed your comments. But have only 1 question - there is no 'general' enum for Credentials in `apiEntities`. I used `OPENSTACK_CREDENTIAL` for credential entity. Is it OK or should I add one more enum `CREDENTIAL`?

2022-03-04 12:46 UTC, stefcameron commented on src/util/helper.js
> +  return `${metadata.cloudUrl}/${metadata.namespace}/type?name=${metadata.name}`;
With what I pushed to master last night, you don't need to pass the entity into the function because you have it in `entity.metadata.kind`, and for credentials, you can check if the `kind` is included in `apiCredentialKinds` values instead of checking for one specific value like the other entities.

2022-03-07 17:41 UTC, stefcameron requested changes

2022-03-07 23:11 UTC, stefcameron requested changes
Aaaaaalllllmoooost there... 😉

2022-03-07 23:11 UTC, stefcameron commented on src/catalog/catalogEntities.js
> +  switch (entity.metadata.kind) {
Somehow we lost the cluster case. 🙂 We need `case apiKinds.CLUSTER` and it should open to the `/clusters/{entity.metadata.name}` page of the MCC instance.

2022-03-08 09:15 UTC, AntonNos commented on src/catalog/catalogEntities.js
> +  switch (entity.metadata.kind) {
Ohh, I didn't add it because had a plan to add it in scope of "Cluster" task. BTW, I added it here:)

2022-03-08 15:55 UTC, stefcameron approved these changes
🎉

2022-03-08 15:55 UTC, stefcameron commented on src/catalog/catalogEntities.js
> +  switch (entity.metadata.kind) {
Oh, OK, I didn't realize that. But thanks for adding it anyway!

2022-03-08 15:55 UTC, merged