[PRODX-22754]: fixed bug with table sorting
Mirantis/lens-extension-cc pull request #806
Opened 2022-03-29 10:50 UTC by AntonNos

- Fixed issue, when sorting was working only with `URL` column
- Fixed visual behaviour of sorting arrow

2022-03-30 23:26 UTC, stefcameron requested changes

2022-03-30 23:26 UTC, stefcameron commented on src/renderer/components/EnhancedTable/EnhancedTableHead.js
> +    opacity: ${({ isSortedByCurrent }) => (isSortedByCurrent ? '1;' : '0;')}
I guess this "hides" it or "shows" it. Could we use the "visibility" style here instead? Set `visibility: visible` or `visibility: hidden` as appropriate. If hidden, it'll hide it without removing it from layout, so it'll maintain its presence and things won't get misaligned. Using "opacity" for this feels like a bit of a hack.

2022-03-30 23:26 UTC, stefcameron commented on src/renderer/components/EnhancedTable/EnhancedTableHead.js
> +  order: PropTypes.string.isRequired,
This would be more useful if it was typed as `order: PropTypes.oneOf(['asc', 'desc']).isRequired`

2022-03-30 23:41 UTC, stefcameron commented
I don't think I was able to reproduce the bug you were talking about in Slack. AFAICT, all the original issues I found are fixed.

But there is one strange thing, which is that even though the status of both Clouds is "Disconnected", toggling the sort order still changes the order. I would've expected the order to remain stable since the values are the same. But I think this is likely related to `Array.sort()` stability not being guaranteed earlier than ECMAScript 2019, and I'm assuming the version of Electron Lens is using might be earlier than that. I can't see what piece of our code would make this unstable.

Sorting the URL when we have 2 Clouds, one with an IP address and one with a domain, may result in the opposite order you expect, but I think that's because "1" comes before "a" in ASCII.

2022-03-31 08:15 UTC, AntonNos commented on src/renderer/components/EnhancedTable/EnhancedTableHead.js
> +    opacity: ${({ isSortedByCurrent }) => (isSortedByCurrent ? '1;' : '0;')}
Fixed

2022-03-31 14:16 UTC, stefcameron approved these changes

2022-03-31 15:46 UTC, merged