[PRODX-24170]: added tests for WelcomeView component
Mirantis/lens-extension-cc pull request #921
Opened 2022-06-14 10:41 UTC by AntonNos

<img width="664" alt="Screenshot 2022-06-14 at 13 39 21" src="https://user-images.githubusercontent.com/33761040/173559165-e9cd57e6-537a-4f8b-b68c-ffedfe51f70d.png">

2022-06-14 21:27 UTC, stefcameron requested changes
Nice work! All comments except one are more for educational purposes than being changes you should make. The one comment about the list item strings, however, needs to be addressed. 😄

2022-06-14 21:27 UTC, stefcameron commented on src/strings.ts
> +  ],
It's OK to remove the HTML markup, but you're using the wrong content. Please use the content from the `master` branch and just remove the markup.

2022-06-14 21:27 UTC, stefcameron commented on src/renderer/components/GlobalPage/WelcomeView.js
> +            primary="true"
This looks like a change to the code to accommodate the test, which is not a good practice.

Though looking at your tests, I don't think you're actually looking for a `button` element that has a `primary` attribute set to `"true"` anywhere, so you can probably just revert this change back to `primary`.

But if I missed something that you're indeed looking for a "primary button", not just a "button", then you should update the Button component's mock to specially-handle a boolean prop named `primary` and do with it what the real Lens component would normally do with it. This is key, because if you just do whatever to get the test to pass, the test is unreliable because it gives us a false-positive (i.e. we think we didn't break anything because the tests passed, when in reality, we may have broken something).

2022-06-14 21:27 UTC, stefcameron commented on src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
> +  it('clicking on button triggers onClick handler', async () => {
This may seem like splitting hairs (i.e. being too particular), but I'm just trying to help you look at tests with the right perspective, so I hope this help.

"clicking on button triggers onClick handler" isn't really relevant to the WelcomePage component. What you want to test is, "clicking on button triggers openAddCloud handler" -- you don't really know (i.e. this component doesn't really know) __how__ that handler is being triggered (could be a click, could be mouse down, could be hover, could be some other event); you just care that it's __being__ triggered.

It's a subtle difference, but it stresses the principal of "separation of concerns", which will serve you extremely well in any code you write. It applies to nearly all things we do as software engineers when we write code or design systems. 😄 

```suggestion
  it('clicking on button triggers openAddCloud handler', async () => {
```

2022-06-14 21:27 UTC, stefcameron commented on src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
> +    expect(welcomeButton).toHaveTextContent(strings.welcome.button.label());
This is nice, but since there's literally not one branch of code in the WelcomeView (i.e. there are no conditional statements), there isn't much value checking all these things. I bet you could remove this test and still be at 100% coverage just with the test that checks the `openAddCloud` handler is called when the button is clicked.

What this will do, however, is cause tests to break if there's the slightest change to the WelcomeView's implementation which would probably inconsequential, which will make tests harder to maintain.

But we can keep this. I'm just pointing out that your time is better spent testing branch logic than it is making sure the right strings are being used.

As for the button, it would be better to use `screen.getByLabelText(strings.welcome.button.label())` than `firstChild.querySelector('button')` to get the element because that would test all these things at once:

1. A button is being used
2. The button is using the expected label
3. There is a single button with that label on the screen.

When you use `firstChild.querySelector('button');`, you're just finding the first button element. There might be another, and even with the same label, but you'll totally miss that.

2022-06-16 06:42 UTC, AntonNos commented on src/strings.ts
> +  ],
Done

2022-06-16 06:43 UTC, AntonNos commented on src/renderer/components/GlobalPage/WelcomeView.js
> +            primary="true"
Updated mocks to to get rid of console error.

2022-06-16 06:45 UTC, AntonNos commented on src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
> +  it('clicking on button triggers onClick handler', async () => {
Understand, thanks

2022-06-16 06:59 UTC, AntonNos commented on src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
> +    expect(welcomeButton).toHaveTextContent(strings.welcome.button.label());
I changed `welcomeButton` to what you said, but received an error, that can't find element with label `strings.welcome.button.label()`.
So I used `getAllByText`, but it found 2 buttons. I updated PR, check please what need to be changed.
Also I understand, that I did a lot of unnecessary tests. Will try no to do them in the future.

2022-06-16 18:52 UTC, stefcameron requested changes
Let's see if we can address that `getAllByText()` issue... 🙂

2022-06-16 18:52 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +};
Since this is directly related to the definition of the mocked Button component on lines 184-190, could we move this up to line 192 and move `export const Renderer = {...}` down? That would make the code more readable.

2022-06-16 18:52 UTC, stefcameron commented on src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
> +    const welcomeButton = screen.getAllByText(strings.welcome.button.label());
This is strange. Why wouldn't `getByLabelText(...)` work here? Also, when combined with `.toBeInTheDocument()`, it's best to use `queryBy...()` queries instead of `getBy` or `getAllBy` because the "get" queries __require__ finding what they're looking for and will throw if not found (so the existence is tied with the query), whereas "query" queries don't require existence (i.e. they can return `null` for `queryBy` and an empty list for `queryAllBy`). You can read about the different types of queries here: https://testing-library.com/docs/queries/about#types-of-queries

So in the end, lines 37 and 60 should come down to this:

```javascript
expect(screen.queryByLabelText(strings.welcome.button.label())).toBeInTheDocument();
```

If for some reason the button doesn't exist, the `queryBy` query will return `null` (instead of `getBy` which would throw), and then the `toBeInTheDocument` assertion will fail the test because `null` indicates it's _not_ in the document.

Otherwise, `queryBy` will return the button, and the assertion will pass.

2022-06-16 20:12 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +};
Sure, let me check all your comments and I will update PR

2022-06-21 19:43 UTC, stefcameron commented on src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
> +      container: { firstChild },
Also, as I mentioned on other PRs, this isn't a good practice. Prefer using `screen` and `document` instead of doing this.

2022-06-22 08:41 UTC, AntonNos commented on src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
> +    } = render(<WelcomeView openAddCloud={() => {}} />);
Thanks! Fixed

2022-06-22 21:07 UTC, stefcameron approved these changes

2022-06-22 21:21 UTC, merged