[PRODX-24171]: Added tests for ErrorPanel and InfoPanel components
Mirantis/lens-extension-cc pull request #929
Opened 2022-06-20 11:05 UTC by AntonNos

<img width="676" alt="Screenshot 2022-06-20 at 14 04 07" src="https://user-images.githubusercontent.com/33761040/174588433-6bc2b374-8230-42e7-bfbe-3d9355da6e23.png">

2022-06-21 19:42 UTC, stefcameron requested changes
Nice coverage!

2022-06-21 19:42 UTC, stefcameron commented on src/renderer/components/__tests__/ErrorPanel.spec.js
> +  it(`renders an Error Panel with |${randomString}| message`, () => {
Since the `randomString` is random, it's not useful having it in the test name like this. I would put the pipes around "with" and "without" between this and the test above it since that's the important difference between the two. So "renders |without| a message" and "renders |with| a message" would be good names for those tests. No need to repeat "Error Panel" because we know these tests are all related to the ErrorPanel from the `describe('/renderer/components/ErrorPanel', () => {` spec title.

2022-06-21 19:42 UTC, stefcameron commented on src/renderer/components/__tests__/ErrorPanel.spec.js
> +      container: { firstChild },
Instead of always getting the first child like this, it's a better practice to use `screen`. When rendered, what you render should always be the only thing that's in the DOM anyway. And using `firstChild` like this might result in hiding multi-render issues with tests like on that other PR for the WelcomeView.

If you need to query for an element, you can just use `document.querySelector()` right there wherever you have `firstChild.querySelector()`.

2022-06-21 19:42 UTC, stefcameron commented on src/renderer/components/__tests__/InfoPanel.spec.js
> +      container: { firstChild },
Same here...

2022-06-21 19:42 UTC, stefcameron commented on src/renderer/components/__tests__/InfoPanel.spec.js
> +  it(`renders an Info Panel with |${randomString}| message`, () => {
Same here...

2022-06-22 09:00 UTC, AntonNos commented on src/renderer/components/__tests__/ErrorPanel.spec.js
> +      container: { firstChild },
Thanks, fixed all comments

2022-06-22 21:07 UTC, stefcameron approved these changes

2022-06-22 21:25 UTC, merged