[PRODX-24171]: added tests for styles
Mirantis/lens-extension-cc pull request #934
Opened 2022-06-21 12:38 UTC by AntonNos

<img width="656" alt="Screenshot 2022-06-21 at 15 34 38" src="https://user-images.githubusercontent.com/33761040/174800770-4391dc43-5485-4de1-8835-53e45934126a.png">

2022-06-21 19:57 UTC, stefcameron requested changes

2022-06-21 19:57 UTC, stefcameron commented on src/renderer/components/__tests__/styles.spec.js
> +  });
I don't think this is worth testing. There's nothing parameterized here, just straight object export. Having a test for this will just make it more work to update the styles.

2022-06-21 19:57 UTC, stefcameron commented on src/renderer/components/__tests__/styles.spec.js
> +        '> *': { marginBottom: 24 },
I think this (line 38) is the only thing that's worth testing here, the expectation that the margin is set to 6 x gap. And I would do it like this instead of hard coding numbers:

```
expect(styles.mixinColumnStyles()['> *'].marginBottom).toBe(styles.layout.grid * 6)
```

That way, if the value of `grid` is changed, the test will survive the change instead of breaking. It'll only break if the gap is made larger/smaller, and maybe that's an interesting double-check to make sure that's what we really meant to do.
```

2022-06-21 19:57 UTC, stefcameron commented on src/renderer/components/__tests__/styles.spec.js
> +          marginBottom: 16,
I would check this as `marginBottom: styles.layout.gap` in case `styles.layout.grid` changes, making `styles.layout.gap` change and resulting in the test breaking. We should just care here that the bottom margin defaults to `styles.layout.gap`.

I'd also not test the rest of the object since it's not really that important.

```
expect(styles.mixinFlexColumnGaps()['> *'].marginBottom).toBe(styles.layout.gap)
```

2022-06-21 19:57 UTC, stefcameron commented on src/renderer/components/__tests__/styles.spec.js
> +          marginBottom: 10,
Again with this, what's most interesting is that the value given as a parameter is used inside as expected, so

```
expect(styles.mixinFlexColumnGaps()['> *'].marginBottom).toBe(10)
```

would be enough for this.

2022-06-22 09:45 UTC, AntonNos commented on src/renderer/components/__tests__/styles.spec.js
> +          marginBottom: 10,
Fixed all comments

2022-06-22 19:20 UTC, stefcameron requested changes
Code looks good now but the PR contains downgrades of packages in package and lock files...

2022-06-22 21:36 UTC, merged