WIP [PRODX-24169]: added tests for EnhancedTableRow component
Mirantis/lens-extension-cc pull request #975
Opened 2022-07-18 07:56 UTC by AntonNos

2022-07-26 17:25 UTC, stefcameron commented
👀

2022-07-26 18:25 UTC, stefcameron requested changes
Thanks for your work on the EnhancedTableRow tests, they look pretty good. Most comments are around the extensions.js mock changes, and updates to other tests related to the new mock Cloud class.

2022-07-26 18:25 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +  Util,
Looks like you've changed the Common.Util module to be a class that renders a URL. That is not a good idea. It might work for now, but it will break other tests down the road. We need to keep the mock definition of Common.Util as it was. If you didn't like that `openExternal(url)` was looking to the console, you can replace `console.log()` with code that creates a new element and inserts it into the DOM as a way of checking what URL was opened, but I would stick with the console statement. That can easily be checked in a test with jest-mock-console.

2022-07-26 18:25 UTC, stefcameron commented on src/common/__tests__/MockCloud.js
>  import { CloudNamespace } from '../CloudNamespace';
MockCloud.js should have been deleted...

2022-07-26 18:25 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/AdditionalInfoRows.spec.js
> +    fakeCloudJson = mkCloudJson({
Unless you need the JSON separately (i.e. because you need to initialize the CloudStore with it), you should just create the Cloud directly instead of having the JSON separate. That will keep the test file more concise and no one will wonder why this JSON variable exists. So just replace this with
```suggestion
    fakeCloud = new Cloud({
```

2022-07-26 18:25 UTC, stefcameron commented on src/renderer/components/EnhancedTable/AdditionalInfoRows.js
> +    <EnhInfoRow>
I'm curious what caused you to add the additional `<tr>` wrapping here. I don't see a change to the component that consumes the `<AdditionalInfoRows>` component, so I'm concerned that it's providing a `<tr>` and now we're ending up with `<tr><tr>...</tr></tr>` in the real code...

2022-07-26 18:25 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/EnhancedTable.spec.js
> +    fakeCloudFooJson = mkCloudJson({
Same comment here about `fakeCloudFooJson` and `fakeCloudBarJson` as on src/renderer/components/EnhancedTable/__tests__/AdditionalInfoRows.spec.js -- these don't appear to be needed independently from Cloud instances in order to initialize the CloudStore. Would be best to just not have them...

2022-07-26 18:25 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/EnhancedTableRow.spec.js
> +      fakeCloudWithoutNamespacesJson;
Same comment here with `fakeCloudFooJson` and `fakeCloudWithoutNamespacesJson` as with src/renderer/components/EnhancedTable/__tests__/AdditionalInfoRows.spec.js -- these aren't needed in this test module to initialize the CloudStore, so best to just not have them.

2022-07-26 18:25 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/EnhancedTableRow.spec.js
> +import mockConsole from 'jest-mock-console';
Nice work on the tests in here! 👍

2022-07-26 18:25 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +  const connectedFakeCloud = new Cloud(connectedFakeCloudJson);
All of these (and the related code above) should be in a `beforeEach()` to make sure that each test that uses them gets a clean set of data.

Also, again, as with src/renderer/components/EnhancedTable/__tests__/AdditionalInfoRows.spec.js, I don't think any of the separate `*FakeCloudJson` variables are needed in this test module. None of them appear to be used to initialize the CloudStore. Best not to have them.

2022-07-26 23:20 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +    ok();
Fixed

2022-07-26 23:20 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +          <button className="ok"></button>
Fixed

2022-07-26 23:39 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +  Util,
Fixed

2022-07-26 23:40 UTC, AntonNos commented on src/common/__tests__/MockCloud.js
>  import { CloudNamespace } from '../CloudNamespace';
Done

2022-07-26 23:43 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/AdditionalInfoRows.spec.js
> +    fakeCloudJson = mkCloudJson({
Done

2022-07-26 23:44 UTC, AntonNos commented on src/renderer/components/EnhancedTable/AdditionalInfoRows.js
> +    <EnhInfoRow>
I added couple of `tr`, `td`, because there was an error with DOM validating. Something like `div` cannot be a child of `tr` etc..

2022-07-26 23:46 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/EnhancedTable.spec.js
> +    fakeCloudFooJson = mkCloudJson({
Fixed

2022-07-26 23:48 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/EnhancedTableRow.spec.js
> +      fakeCloudWithoutNamespacesJson;
Done

2022-07-26 23:48 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/EnhancedTableRow.spec.js
> +import mockConsole from 'jest-mock-console';
Thanks!

2022-07-26 23:54 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +  const connectedFakeCloud = new Cloud(connectedFakeCloudJson);
I didn't put them in `beforeEach()`, because I have a loop: 
```
[disconnectedFakeCloud, connectingFakeCloud, connectedFakeCloud].forEach((cloud) => {
  it()
})
```.
And if I put them in `beforeEach(),` all of them are not defined --> `cloud` is `undefined`

2022-07-27 00:02 UTC, stefcameron commented
👀

2022-07-27 00:20 UTC, stefcameron requested changes
Great updates! Just a few more loose ends to tie off.

2022-07-27 00:20 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +    const { ok } = props;
Also handle `cancel` prop here; otherwise, when comes time to test the cancel for some future test, things will break and it'll require more time then to figure out why it's not working than it does now, knowing how it will fail... 🙂

2022-07-27 00:20 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +    this.state.ok();
Don't assume `ok` is defined. Use `this.state.ok?.()` (optional chaining; I think that's the syntax for an optional function call)

Also need to set `isOpen` state to false here too since OK also dismissed the modal.

2022-07-27 00:20 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +    const fetchingFakeCloudJson = mkCloudJson({
You seem to have gone back to JSON from Cloud, but you're not using the JSON to initialize the CloudStore... Any reason why you went back to JSON?

2022-07-27 00:20 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +        const fakeCloudJson = mkCloudJson({
Same here?

2022-07-27 00:20 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +    const fakeCloudJson = mkCloudJson({
Same here?

2022-07-27 00:20 UTC, stefcameron commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
>    [disconnectedFakeCloud, connectingFakeCloud, connectedFakeCloud].forEach(
Since these clouds are really test cases as well as test data, make them consts and localize them to this particular test. I'm just concerned that having them in the outer scope will result in someone writing a test in the future using one of these, having the test modify it, without realizing that they aren't rebuilt with a `beforeEach()` on every test, and then we end-up with a really hard-to-find bug where one test depends on another's output.

So like this:

```suggestion
    (function () {
      const disconnectedFakeCloud = new Cloud(...);
      const connectingFakeCloud = new Cloud(...);
      const connectingFakeCloud = new Cloud(...);
      
      [disconnectedFakeCloud, connectingFakeCloud, connectedFakeCloud].forEach(
        ...
      );
    })();
```

2022-07-27 09:53 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +    this.state.ok();
Done

2022-07-27 09:56 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +    const fetchingFakeCloudJson = mkCloudJson({
Hmm, maybe I missed that. Fixed

2022-07-27 09:56 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +        const fakeCloudJson = mkCloudJson({
Fixed

2022-07-27 09:56 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
> +    const fakeCloudJson = mkCloudJson({
Fixed

2022-07-27 10:02 UTC, AntonNos commented on src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js
>    [disconnectedFakeCloud, connectingFakeCloud, connectedFakeCloud].forEach(
Hmm, good solution! Thank you, fixed

2022-07-27 16:43 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +    const { ok } = props;
Thanks, but what you did is not what I was asking. 🙂 `cancel` is another prop like `ok` that the consumer can provide to the ConfirmDialog component and its `open()` method. The changes you made are still not handling this case. Handle the `cancel` prop the same way you're handling the `ok` prop.

2022-07-27 18:35 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +    const { ok } = props;
Oh, I understand what you mean. Fixed

2022-07-27 19:26 UTC, stefcameron requested changes

2022-07-27 19:26 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +          <button className="cancel" onClick={this.state.cancel}></button>
```suggestion
          <button className="cancel" onClick={this.cancel}></button>
```

2022-07-27 19:26 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +      ...this.state,
Spreading the existing state into the state updater isn't necessary. React will take the object you give it here and shallow-merge it with the full existing state.

2022-07-27 19:26 UTC, stefcameron commented on __mocks__/@k8slens/extensions.js
> +      ...this.state,
Spreading the existing state into the state updater isn't necessary. React will take the object you give it here and shallow-merge it with the full existing state.

2022-07-27 19:30 UTC, AntonNos commented on __mocks__/@k8slens/extensions.js
> +          <button className="cancel" onClick={this.state.cancel}></button>
Missed it, sorry

2022-07-27 20:23 UTC, stefcameron approved these changes
👌

2022-07-27 20:46 UTC, merged